apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: telsha-ca
  namespace: cert-manager-trust
spec:
  commonName: cluster.local
  isCA: true
  issuerRef:
    name: telsha-selfsigned
    kind: ClusterIssuer
  secretName: telsha-ca
