apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  annotations:
    automata.shikanime.studio/images: '[ { "name": "honcho", "tag-regex": "^(?P<version>.+)$" }, { "name": "honcho-postgres", "tag-regex": "^(?P<version>.+)$" } ]'
images:
  - name: honcho
    newName: ghcr.io/plastic-labs/honcho
    newTag: latest
  - name: honcho-postgres
    newName: pgvector/pgvector
    newTag: pg15
configMapGenerator:
  - files:
      - honcho-postgres/init.sql
    name: honcho-postgres
secretGenerator:
  - envs:
      - honcho/.enc.env
    name: honcho
  - envs:
      - honcho-postgres/.enc.env
    name: honcho-postgres
    type: basic-auth
patches:
  - path: patch-sts.yaml
resources:
  - deploy.yaml
  - svc.yaml
  - sts.yaml
