---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hermes-agent
spec:
  template:
    spec:
      enableServiceLinks: true
      containers:
        - name: hermes-agent
          env:
            - name: HONCHO_BASE_URL
              value: http://$(HONCHO_SERVICE_HOST):$(HONCHO_SERVICE_PORT)
