---
resources:
  - ../../base
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: backend-service
      app.kubernetes.io/instance: catbox
      app.kubernetes.io/name: catbox
      app.kubernetes.io/part-of: telsha-workstation
      app.kubernetes.io/version: 0.17.1
