apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nishir
spec:
  ca:
    secretName: nishir-ca
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nishir-gateway
spec:
  acme:
    email: nishir@shikanime.studio
    privateKeySecretRef:
      name: nishir-gateway-private-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            ingressClassName: tailscale
            ingressTemplate:
              metadata:
                annotations:
                  tailscale.com/funnel: "true"
                  tailscale.com/tags: tag:web
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nishir-selfsigned
spec:
  selfSigned: {}
