---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-tailscale
  interval: 10m
  path: ./infrastructure/longhorn/overlays/nishir
  prune: true
  deletionPolicy: Orphan
  healthChecks:
    - name: longhorn-hetzner-backups
      apiVersion: v1
      kind: Secret
      namespace: longhorn-system
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-longhorn-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
  interval: 10m
  path: ./configs/longhorn/overlays/nishir
  prune: true
  deletionPolicy: Orphan
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
