apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: tofu-controller
      version: "0.19.x"
      sourceRef:
        kind: HelmRepository
        name: tofucontroller
        namespace: flux-system
  values:
    # Reconciliation interval for Terraform CRs
    reconciliationInterval: 600
    # Install CRDs
    installCRDs: true
