analytics:
  url: https://api.segment.io/v1/track
  token: null
  user_id: null
appservice:
  id: meta
  address: http://mautrix-meta:29319
  as_token: ENC[AES256_GCM,data:U+mcbm0Jx7TJKbJNlh6Fggfdw9vedH7k2m09U7iSdyiI7lWY5W/AZFstEECRlhCMy4U4N9FxvXHozyIg3iPKsw==,iv:Ch21Dck/Dz/wNAy+5/ULdlCFz9wA7XGw/yt/xjc6pNI=,tag:vLg2Y1g7sMghq4q3p5IXvQ==,type:str]
  async_transactions: false
  ephemeral_events: true
  hostname: 0.0.0.0
  hs_token: ENC[AES256_GCM,data:YdoOMi2R8EhZWvVNulapNqKYHzE1CGHxe591ZsyayzXJgdJJXmY/X8vgKWiNul4I/1IG9rXgKhhO2jvLvif7sw==,iv:mA0PbO2KQfnExKz27j0QCywY4Gwz5QByIktC6tPg2ag=,tag:LOmylz/blM0BftUfa0Vo6A==,type:str]
  port: 29319
  public_address: https://matrix-meta.taila659a.ts.net
  username_template: meta_{{.}}
  bot:
    avatar: mxc://maunium.net/DxpVrwwzPUwaUSazpsjXgcKB
    displayname: Meta bridge bot
    username: metabot
backfill:
  enabled: true
  max_catchup_messages: 500
  max_initial_messages: 50
  queue:
    batch_delay: 20
    batch_size: 100
    enabled: false
    max_batches: -1
    max_batches_override: {}
  threads:
    max_initial_messages: 50
  unread_hours_threshold: 720
bridge:
  async_events: false
  bridge_matrix_leave: false
  bridge_notices: false
  bridge_status_notices: errors
  cleanup_on_logout:
    bad_credentials:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
    enabled: false
    manual:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
  command_prefix: "!meta"
  cross_room_replies: false
  deduplicate_matrix_messages: false
  mute_only_on_create: true
  no_bridge_info_state_key: false
  only_bridge_tags:
    - m.favourite
    - m.lowpriority
  permissions:
    "*": relay
    "@root:matrix.taila659a.ts.net": admin
    matrix.taila659a.ts.net: user
  personal_filtering_spaces: true
  private_chat_portal_meta: true
  relay:
    admin_only: true
    default_relays: []
    displayname_format: "{{ .DisambiguatedName }}"
    enabled: false
    message_formats:
      m.audio:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent an audio file{{ if .Caption
        }}: {{ .Caption }}{{ end }}"
      m.emote: "* <b>{{ .Sender.DisambiguatedName }}</b> {{ .Message }}"
      m.file:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a file{{ if .Caption }}: {{
        .Caption }}{{ end }}"
      m.image:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent an image{{ if .Caption }}:
        {{ .Caption }}{{ end }}"
      m.location:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a location{{ if .Caption
        }}: {{ .Caption }}{{ end }}"
      m.notice: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.text: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.video:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a video{{ if .Caption }}:
        {{ .Caption }}{{ end }}"
  resend_bridge_info: false
  split_portals: false
  tag_only_on_create: true
  unknown_error_auto_reconnect: null
database:
  type: sqlite3-fk-wal
  max_conn_idle_time: null
  max_conn_lifetime: null
  max_idle_conns: 1
  max_open_conns: 5
  uri: file:/data/mautrix-meta.db?_txlock=immediate
direct_media:
  allow_proxy: true
  enabled: false
  media_id_prefix: null
  server_key: ENC[AES256_GCM,data:cUaJB7+jk85OUtjgaVrd7/JlS2PZ5a+e6xLAXITX1T8TDiGA6K1nAVKBzhRnhLym/+jt6OQvcbAQng==,iv:KI0UReU7aSJ0g127MmHNhvYVHIHmJicGKJn7dltqvH0=,tag:j330mIRykTvggRR4FlTCtw==,type:str]
  server_name: matrix-discord-media.taila659a.ts.net
  well_known_response: null
double_puppet:
  allow_discovery: false
  secrets:
    matrix.taila659a.ts.net: ENC[AES256_GCM,data:qtAC1YWl0nDfbjwQxXAjxQxCSnohrf2i95+Ye3C9bwTRdebyWOV3D4dxc9hKudZA+5AaWINCsVZt+JFEDgclZx0GoVmEQyEzng==,iv:cioPcNRdtRPfYwdWFeDoyBRJkCyrrm8/4LCmxqTTeq4=,tag:yjmwAf9PEhg29VePd40sqw==,type:str]
  servers:
    anotherserver.example.org: https://matrix.anotherserver.example.org
encryption:
  allow: true
  allow_key_sharing: true
  appservice: false
  default: true
  delete_keys:
    delete_fully_used_on_decrypt: true
    delete_on_device_delete: true
    delete_outbound_on_ack: false
    delete_outdated_inbound: true
    delete_prev_on_new_session: true
    dont_store_outbound: true
    periodically_delete_expired: true
    ratchet_on_decrypt: true
  msc4190: false
  pickle_key: ENC[AES256_GCM,data:tbGGYRFHJmwpf9P10wFHC9t8+jtW5t+wxBm1/3qIDdu67cmW8js5fgTLN2WABR/nPoPKfnIke+9vwMUbfBiALQ==,iv:qAy5Ow37k9oz1vBNvvM3QvRKDRu2hXcjjUJGz7KTKtA=,tag:cFUl8vJJrt4GAI/RkRWZQA==,type:str]
  require: false
  rotation:
    disable_device_change_key_rotation: false
    enable_custom: false
    messages: 100
    milliseconds: 6.048e+08
  self_sign: true
  verification_levels:
    receive: cross-signed-tofu
    send: cross-signed-tofu
    share: cross-signed-tofu
homeserver:
  address: https://synapse:8448
  async_media: false
  domain: matrix.taila659a.ts.net
  message_send_checkpoint_endpoint: null
  ping_interval_seconds: 0
  software: standard
  status_endpoint: null
  websocket: false
logging:
  min_level: debug
  writers:
    - type: stdout
      format: pretty-colored
    - type: file
      compress: false
      filename: ./logs/bridge.log
      format: json
      max_backups: 10
      max_size: 100
matrix:
  delivery_receipts: false
  federate_rooms: true
  message_error_notices: true
  message_status_events: false
  sync_direct_chat_list: true
  upload_file_threshold: 5.24288e+06
network:
  allow_messenger_com_on_fb: false
  cache_connection_state: false
  disable_xma_always: false
  disable_xma_backfill: true
  displayname_template: '{{or .DisplayName .Username "Unknown user"}}'
  force_refresh_interval_seconds: 72000
  get_proxy_from: null
  ig_e2ee: false
  min_full_reconnect_interval_seconds: 3600
  mode: null
  proxy: null
  proxy_media: false
  receive_instagram_typing_indicators: true
  send_presence_on_typing: false
provisioning:
  allow_matrix_auth: true
  debug_endpoints: false
  enable_session_transfers: false
  shared_secret: ENC[AES256_GCM,data:yhTz+LHnOHcnGXfiHhQD0+XjKLWuVgUn6sy/tZtAOJm2/kpN2AhhcEyEtRlD3QYZE1aLCSw5yo/ae7Rn8BtTkw==,iv:6BNKPCxaDPFUI4xJ4+b9es+BBOc0OijLi2stJFsVNxo=,tag:otF+0NCTcHsz1Ru7U+FHtQ==,type:str]
public_media:
  enabled: false
  expiry: 0
  hash_length: 32
  signing_key: ENC[AES256_GCM,data:kNsueDlI8PCrtv0nT0eDHAo8mv//Eun/pvvS1XE2aToYMYM6TOhmDEB7qmVheOUzYr/GDGlR3VmZozU9A0jZtQ==,iv:NT9xFON5apLuxL3uIs/7Po2ph0cib4YCTm+YCEhXrw8=,tag:UjRjVjmEhljFHxU8Gu23Ow==,type:str]
sops:
  version: 3.12.2
  encrypted_regex: ^(avatar_proxy_key|as_token|hs_token|pickle_key|server_key|shared_secret|signing_key|login_shared_secret_map|secrets)$
  lastmodified: "2026-04-14T23:44:30Z"
  mac: ENC[AES256_GCM,data:P08lSU9GMlopI6dA7X4r9l6rn/zT1gGo7OY1zlzuc70tpcC7PEvBng3pjNnVdlEgiLgZTyJMebTBRYQUxqCIdQ8vhOCjAaqqxPuXhC6pf0GwKdU4EV63uFra5FfxYXIOOTA6lDiJgsiRWlCJmTzy+h3WErUjcsEluek/iKMp+rA=,iv:dIGjL3FBAFlMSYCjwijYssMn69TE2XGTBqFQzj3jEK0=,tag:0/4bZsCbvVJ43cLfmmngKg==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdWdxNGwrSFRYcG8xdEpx
        YTVYWGJqMWlvc09jY2h6S24rS0pkTUlXc2owCnRHZ2lSdUxXeU5CRXVydlZLTGVs
        cGdBMmJiYWExNXZ1QjMrUHRzTkYyRjAKLS0tIFBhNXBiM20wZjZLWTdyY1NEN3FW
        TXIvNk1SM2gwVjdPc1JtWEN5QkpvSE0KeaGFo4kXO3pNxI3YOD7sVGVE48UrQeEu
        PHq21y5LIWCsgLyKSm4kkr42tPw6UZ/Fsj3f9zU83/SB1QNGX2pFjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTFJYTXJQUGJRZEJXK3NP
        MVU1VGlPR0U5bkR4ZE1CdEVUbkNxdTN6QUVRCk1kdE1heTBiT2VSb1lYTlhNOGQx
        RzFVUXNXTEltb3o5aXEvRWw2YXlyakkKLS0tIG9Oc0dmWXkxR0lobnpqVlFFMFBs
        VHU4cUs2blY1RnZlMlgyQUVLcHlNeFEKX/LZhrhw9Y7E/spmVYa3xxYJya6sEQA4
        AVKNSbKIWELFWc+Xu+TxjVhpVqEFMU2njln/hVeLc8T1lFrCWFvBdA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUzlabFFrcDNzZ2Q0blRR
        STlnaTYraGJTZk42UVYxdmFGTHdIaldsWFMwClhsOUVXcEpQTm9tYzQwakJIMVdk
        dGIvd2I1Yno2Y201VTUxM05lS3REUHMKLS0tIDU4SVpsWVJoSkN3elFVR3I3ZUM5
        WkRDbkh4NnM4MjdoQWtDNHNsczFGTzgK1gkjeSb1vb6wsbOWkhXebVMO1zZAjJf3
        5KcjFTLTK2PmN1x24J/8P2vOxYtDcinPVbkAWr4XNJjxFNGAtEkVXQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
