---
resources:
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "rclone", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" },
      { "name": "synapse", "tag-regex": "^v(?P<version>\\d+\\.\\d+\\.\\d+)$" } ]'
images:
  - name: rclone
    newName: rclone/rclone
    newTag: 1.73.3
  - name: synapse
    newName: matrixdotorg/synapse
    newTag: v1.150.0
configMapGenerator:
  - name: synapse-rclone
    namespace: shikanime
    files:
      - rclone/rclone.conf
labels:
  - pairs:
      app.kubernetes.io/component: communication
      app.kubernetes.io/name: synapse
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 1.140.0
