---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: synapse
spec:
  replicas: 1
  serviceName: synapse
  selector:
    matchLabels:
      app.kubernetes.io/instance: synapse
      app.kubernetes.io/name: synapse
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: synapse
        app.kubernetes.io/name: synapse
    spec:
      initContainers:
        - name: config-sync
          image: rclone
          command:
            - sh
            - -c
            - |
              # Copy synapse config
              rclone copy \
                --copy-links \
                --filter "+ /*.log.config" \
                --filter "+ /*.signing.key" \
                --filter "+ /homeserver.yaml" \
                --filter "- *" \
                --update \
                /mnt/config \
                /mnt/data

              # Copy doublepuppet to synapse appservices
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-discord-config/doublepuppet.yaml \
                /mnt/data/appservices/matrix-discord-doublepuppet.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-googlechat-config/doublepuppet.yaml \
                /mnt/data/appservices/matrix-googlechat-doublepuppet.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-linkedin-config/doublepuppet.yaml \
                /mnt/data/appservices/matrix-linkedin-doublepuppet.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-meta-config/doublepuppet.yaml \
                /mnt/data/appservices/matrix-meta-doublepuppet.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-signal-config/doublepuppet.yaml \
                /mnt/data/appservices/matrix-signal-doublepuppet.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-slack-config/doublepuppet.yaml \
                /mnt/data/appservices/matrix-slack-doublepuppet.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-twitter-config/doublepuppet.yaml \
                /mnt/data/appservices/matrix-twitter-doublepuppet.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-whatsapp-config/doublepuppet.yaml \
                /mnt/data/appservices/matrix-whatsapp-doublepuppet.yaml

              # Copy registration to synapse appservices
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-discord-config/registration.yaml \
                /mnt/data/appservices/matrix-discord.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-googlechat-config/registration.yaml \
                /mnt/data/appservices/matrix-googlechat.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-linkedin-config/registration.yaml \
                /mnt/data/appservices/matrix-linkedin.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-meta-config/registration.yaml \
                /mnt/data/appservices/matrix-meta.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-signal-config/registration.yaml \
                /mnt/data/appservices/matrix-signal.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-slack-config/registration.yaml \
                /mnt/data/appservices/matrix-slack.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-twitter-config/registration.yaml \
                /mnt/data/appservices/matrix-twitter.yaml
              rclone copyto \
                --copy-links \
                --update \
                /mnt/matrix-whatsapp-config/registration.yaml \
                /mnt/data/appservices/matrix-whatsapp.yaml
          volumeMounts:
            - name: config
              mountPath: /mnt/config
              readOnly: true
            - name: data
              mountPath: /mnt/data
            - name: matrix-discord-config
              mountPath: /mnt/matrix-discord-config
              readOnly: true
            - name: matrix-googlechat-config
              mountPath: /mnt/matrix-googlechat-config
              readOnly: true
            - name: matrix-linkedin-config
              mountPath: /mnt/matrix-linkedin-config
              readOnly: true
            - name: matrix-meta-config
              mountPath: /mnt/matrix-meta-config
              readOnly: true
            - name: matrix-signal-config
              mountPath: /mnt/matrix-signal-config
              readOnly: true
            - name: matrix-slack-config
              mountPath: /mnt/matrix-slack-config
              readOnly: true
            - name: matrix-twitter-config
              mountPath: /mnt/matrix-twitter-config
              readOnly: true
            - name: matrix-whatsapp-config
              mountPath: /mnt/matrix-whatsapp-config
              readOnly: true
            - name: rclone-config
              mountPath: /config/rclone/rclone.conf
              subPath: rclone.conf
              readOnly: true
      containers:
        - name: synapse
          image: synapse
          ports:
            - name: http
              containerPort: 8008
            - name: metrics
              containerPort: 9090
          readinessProbe:
            httpGet:
              path: /_matrix/client/versions
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 20
            periodSeconds: 20
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /_matrix/client/versions
              port: http
            initialDelaySeconds: 120
            timeoutSeconds: 30
            periodSeconds: 30
            failureThreshold: 15
          startupProbe:
            httpGet:
              path: /_matrix/client/versions
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 180
          volumeMounts:
            - name: data
              mountPath: /data
      securityContext:
        fsGroup: 991
      volumes:
        - name: config
          secret:
            secretName: synapse
        - name: data
          persistentVolumeClaim:
            claimName: synapse-data
        - name: matrix-discord-config
          secret:
            secretName: mautrix-discord
        - name: matrix-googlechat-config
          secret:
            secretName: mautrix-googlechat
        - name: matrix-linkedin-config
          secret:
            secretName: mautrix-linkedin
        - name: matrix-twitter-config
          secret:
            secretName: mautrix-twitter
        - name: matrix-meta-config
          secret:
            secretName: mautrix-meta
        - name: matrix-signal-config
          secret:
            secretName: mautrix-signal
        - name: matrix-slack-config
          secret:
            secretName: mautrix-slack
        - name: matrix-whatsapp-config
          secret:
            secretName: mautrix-whatsapp
        - name: rclone-config
          configMap:
            name: synapse-rclone
