apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ks.yaml
  - vmscrape-cert-manager.yaml
  - vmscrape-gatekeeper.yaml
  - vmscrape-longhorn.yaml
  - vmscrape-descheduler.yaml
  - vmscrape-synapse.yaml
