apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cert-manager
  namespace: cert-manager-system
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
      - cert-manager-system
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 60s
      scrapeTimeout: 30s
