apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: manash
  namespace: longhorn-system
spec:
  name: manash
  allowScheduling: true
  tags:
    - storage
    - worker
  disks:
    default-disk-1030200000000:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/
      storageReserved: 299592448819
      tags:
        - balanced
        - fast
