---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: fushi
  namespace: longhorn-system
spec:
  name: fushi
  allowScheduling: true
  tags:
    - storage
  disks:
    fushi:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/
      storageReserved: 287919575138
      tags:
        - balanced
        - fast
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: minish
  namespace: longhorn-system
spec:
  name: minish
  allowScheduling: true
  tags:
    - storage
  disks:
    minish:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/
      storageReserved: 287919575138
      tags:
        - balanced
        - fast
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: nishir
  namespace: longhorn-system
spec:
  name: nishir
  allowScheduling: true
  tags:
    - control-plane
  disks:
    flandre:
      allowScheduling: true
      diskType: filesystem
      path: /mnt/flandre/longhorn/
      storageReserved: 2399829082767
      tags:
        - balanced
    nishir:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/
      storageReserved: 76772540416
      tags:
        - critical
    remilia:
      allowScheduling: true
      diskType: filesystem
      path: /mnt/remilia/longhorn/
      storageReserved: 2399829082767
      tags:
        - balanced
