apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: manash
  namespace: longhorn-system
spec:
  name: manash
  allowScheduling: true
  tags:
    - storage
    - worker
  disks:
    flandre:
      allowScheduling: true
      diskType: filesystem
      path: /mnt/flandre/longhorn/
      storageReserved: 2399829082767
      tags:
        - balanced
    remilia:
      allowScheduling: true
      diskType: filesystem
      path: /mnt/remilia/longhorn/
      storageReserved: 2399829082767
      tags:
        - balanced
