---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: whisparr
spec:
  template:
    spec:
      containers:
        - name: whisparr
          volumeMounts:
            - name: sukebe-data
              mountPath: /data/sukebe
              subPath: Sukebe
            - name: sukebe-data
              mountPath: /downloads
              subPath: Staging
      volumes:
        - name: sukebe-data
          persistentVolumeClaim:
            claimName: sukebe-data
