---
resources:
  - ../nishir
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: database
      app.kubernetes.io/instance: hermes-agent-postgres
      app.kubernetes.io/name: hermes-agent-postgres
      app.kubernetes.io/part-of: nishir-automata
      app.kubernetes.io/version: "15"
