apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  values:
    defaultSettings:
      storageNetwork: longhorn-system/longhorn-storage
    networkPolicies:
      type: rke2
      enabled: true
    persistence:
      defaultDiskSelector:
        enable: true
        selector: fast
