apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-slack
spec:
  template:
    spec:
      volumes:
        - name: certs
          configMap:
            name: nishir-ca-certificates.crt
