apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: metatube
  namespace: shikanime
  labels:
    app.kubernetes.io/name: metatube
    app.kubernetes.io/part-of: metatube
spec:
  endpoints:
    - interval: 60s
      path: /metrics
      port: metrics
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
      - shikanime
  selector:
    matchLabels:
      app.kubernetes.io/instance: metatube
      app.kubernetes.io/name: metatube
