resources:
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: rclone
    newName: rclone/rclone
    newTag: 1.71.2
  - name: hermes-agent
    newName: nousresearch/hermes-agent
    newTag: v2026.6.5
metadata:
  annotations:
    automata.shikanime.studio/images: '[ { "name": "hermes-agent", "tag-regex": "^(?P<version>.+)$" } ]'
configMapGenerator:
  - name: hermes-agent-gateway-rclone
    files:
      - rclone/rclone.conf
