---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hermes-agent-gateway
spec:
  targetRef:
    name: hermes-agent-gateway
    apiVersion: apps/v1
    kind: StatefulSet
  updatePolicy:
    updateMode: Auto
