apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syncthing
spec:
  template:
    spec:
      containers:
        - name: syncthing
          livenessProbe:
            httpGet:
              scheme: HTTPS
          readinessProbe:
            httpGet:
              scheme: HTTPS
          startupProbe:
            httpGet:
              scheme: HTTPS
          volumeMounts:
            - name: tls
              mountPath: /config/https-cert.pem
              readOnly: true
              subPath: tls.crt
            - name: tls
              mountPath: /config/https-key.pem
              readOnly: true
              subPath: tls.key
      volumes:
        - name: tls
          secret:
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                mode: 416
                path: tls.key
            secretName: syncthing-tls
