---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-nishir-ca-certificates-volume
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: spec.volumes[name:certs]
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value:
        name: certs
        configMap:
          name: nishir-ca-certificates.crt
    pathTests:
      - condition: MustNotExist
        subPath: spec.volumes[name:certs]
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-nishir-ca-certificates-volume-mount
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: 'spec.containers[name:*].volumeMounts[mountPath:"/etc/ssl/certs"]'
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value:
        name: certs
        mountPath: /etc/ssl/certs
        readOnly: true
    pathTests:
      - condition: MustExist
        subPath: spec.volumes[name:certs]
      - condition: MustNotExist
        subPath: 'spec.containers[name:*].volumeMounts[mountPath:"/etc/ssl/certs"]'
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-init-nishir-ca-certificates-volume-mount
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: 'spec.initContainers[name:*].volumeMounts[mountPath:"/etc/ssl/certs"]'
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value:
        name: certs
        mountPath: /etc/ssl/certs
        readOnly: true
    pathTests:
      - condition: MustExist
        subPath: spec.initContainers
      - condition: MustExist
        subPath: spec.volumes[name:certs]
      - condition: MustNotExist
        subPath: 'spec.initContainers[name:*].volumeMounts[mountPath:"/etc/ssl/certs"]'
