---
resources:
  - ../nishir
  - netpol.yaml
namespace: shikanime
patches:
  - path: patch-ingress.yaml
configMapGenerator:
  - name: synapse-proxy
    files:
      - synapse-proxy/Caddyfile
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: communication
      app.kubernetes.io/instance: synapse-proxy
      app.kubernetes.io/name: synapse-proxy
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 2.11.2
