apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - synapse-proxy/Caddyfile
    name: synapse-proxy
namespace: shikanime
patches:
  - path: patch-ingress.yaml
resources:
  - ../nishir
  - netpol.yaml
  - proxyclass.yaml
