---
resources:
  - ingress.yaml
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "whisparr", "tag-regex":
      "^v(?P<channel>\\d+)-(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(?:\\.(?P<build>\\d+))?$"
      }, { "name": "radarr", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" }
      ]'
images:
  - name: radarr
    newName: lscr.io/linuxserver/radarr
    newTag: 6.0.4
  - name: rclone
    newName: rclone/rclone
    newTag: 1.71.2
configMapGenerator:
  - name: radarr-rclone
    namespace: shikanime
    files:
      - rclone/rclone.conf
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: library-manager
      app.kubernetes.io/instance: radarr
      app.kubernetes.io/name: radarr
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 6.0.4
