---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: radarr
spec:
  targetRef:
    name: radarr
    apiVersion: apps/v1
    kind: StatefulSet
  updatePolicy:
    updateMode: Auto
