apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea-mirror
spec:
  template:
    spec:
      volumes:
        - name: certs
          configMap:
            name: nishir-ca-certificates.crt
        - name: tls
          secret:
            secretName: forgejo-tls
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
                mode: 0640
