apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: shikanime
profiles:
  - name: nishir-tailnet
    activation:
      - kubeContext: nishir
    manifests:
      hooks:
        before:
          - host:
              command:
                - devenv
                - tasks
                - run
                - sops:decrypt
        after:
          - host:
              command:
                - devenv
                - tasks
                - run
                - sops:cleanup
      kustomize:
        paths:
          - clusters/nishir/overlays/tailnet
  - name: telsha-tailnet
    activation:
      - kubeContext: rancher-desktop
    manifests:
      hooks:
        before:
          - host:
              command:
                - devenv
                - tasks
                - run
                - sops:decrypt
        after:
          - host:
              command:
                - devenv
                - tasks
                - run
                - sops:cleanup
      kustomize:
        paths:
          - clusters/telsha/overlays/tailnet
