---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: shikanime
build:
  artifacts:
    - image: ghcr.io/shikanime/manifests/qbittorrent-resume
      context: cmd/qbittorrent-resume
      ko: {}
      platforms:
        - linux/amd64
        - linux/arm64
profiles:
  - name: nishir-tailnet
    activation:
      - kubeContext: nishir-k8s-operator.taila659a.ts.net
    manifests:
      kustomize:
        paths:
          - clusters/nishir/overlays/tailnet
  - name: telsha-tailnet
    activation:
      - kubeContext: rancher-desktop
    manifests:
      kustomize:
        paths:
          - clusters/telsha/overlays/tailnet
