---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lidarr
spec:
  template:
    spec:
      containers:
        - name: lidarr
          volumeMounts:
            - name: music-data
              mountPath: /data/music
            - name: downloads-data
              mountPath: /downloads
      volumes:
        - name: music-data
          persistentVolumeClaim:
            claimName: music-data
        - name: downloads-data
          persistentVolumeClaim:
            claimName: downloads-data
