apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: flux-system
spec:
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: remove
                path: /spec/tls
            target:
              name: telsha-telemetry
              version: v1
              kind: Ingress
  values:
    grafana:
      persistence:
        storageClassName: local-path
    vmsingle:
      spec:
        extraArgs:
          enableTCP6: "true"
        storage:
          resources:
            requests:
              storage: 8Gi
          storageClassName: local-path
      ingress:
        annotations:
          tailscale.com/funnel: "true"
          tailscale.com/tags: tag:web
        enabled: true
        hosts:
          - telsha-telemetry
        ingressClassName: tailscale
