apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: flux-system
spec:
  values:
    grafana:
      persistence:
        enabled: false
    vmsingle:
      spec:
        storageClassName: ""
