---
resources:
  - ../nishir
  - netpol.yaml
namespace: shikanime
patches:
  - path: patch-ingress.yaml
  - path: patch-svc.yaml
configMapGenerator:
  - name: copyparty
    files:
      - ./copyparty/config.conf
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: file-server
      app.kubernetes.io/instance: copyparty
      app.kubernetes.io/name: copyparty
      app.kubernetes.io/part-of: nishir-operation
      app.kubernetes.io/version: 1.20.0
