---
resources:
  - ../nishir
  - netpol.yaml
  - proxyclass.yaml
namespace: shikanime
patches:
  - path: patch-ingress.yaml
  - path: patch-svc.yaml
configMapGenerator:
  - name: copyparty
    files:
      - ./copyparty/config.conf
