resources:
  - ../nishir
  - netpol.yaml
  - ingress.yaml
namespace: shikanime
patches:
  - path: patch-svc.yaml
  - path: patch-sts-oidc.yaml
configMapGenerator:
  - name: copyparty
    files:
      - ./copyparty/config.conf
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: file-server
      app.kubernetes.io/instance: copyparty
      app.kubernetes.io/name: copyparty
      app.kubernetes.io/part-of: nishir-operation
      app.kubernetes.io/version: 1.20.16
secretGenerator:
  - name: copyparty-oidc
    files:
      - oidc.conf=copyparty/oidc.enc.conf
