apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix-linkedin
spec:
  defaultBackend:
    service:
      name: matrix-linkedin
      port:
        name: http
  tls:
    - hosts:
        - matrix-linkedin
