apiVersion: v1
kind: Service
metadata:
  name: matrix-linkedin
spec:
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 29341
      targetPort: http
  selector:
    app.kubernetes.io/name: matrix-linkedin
