---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: qbittorrent-resume
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: qbittorrent-resume
            app.kubernetes.io/name: qbittorrent-resume
        spec:
          containers:
            - name: qbittorrent-resume
              image: qbittorrent-resume
              command:
                - qbittorrent-resume.sh
              securityContext:
                readOnlyRootFilesystem: false
              volumeMounts:
                - name: scripts
                  mountPath: /usr/local/bin
                - name: apk-cache
                  mountPath: /var/cache/apk
              env:
                - name: QBT_URL
                  value: https://$(QBITTORRENT_SERVICE_HOST):$(QBITTORRENT_SERVICE_PORT)
              envFrom:
                - secretRef:
                    name: qbittorrent
          restartPolicy: Never
          volumes:
            - name: scripts
              configMap:
                name: qbittorrent-scripts
                defaultMode: 0755
            - name: apk-cache
              emptyDir: {}
  schedule: "*/2 * * * *"
