---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: qbittorrent-resume
spec:
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app.kubernetes.io/component: qbittorrent-resume
        spec:
          containers:
            - name: qbittorrent-resume
              image: alpine
              command:
                - qbittorrent-resume.sh
              volumeMounts:
                - name: scripts
                  mountPath: /usr/local/bin
                - name: apk-cache
                  mountPath: /var/cache/apk
              envFrom:
                - secretRef:
                    name: qbittorrent
          restartPolicy: OnFailure
          volumes:
            - name: scripts
              configMap:
                name: qbittorrent-scripts
                defaultMode: 0755
            - name: apk-cache
              emptyDir: {}
  schedule: "*/2 * * * *"
