---
resources:
  - cronjob.yaml
  - ingress.yaml
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "alpine", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" },
      { "name": "qbittorrent", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$",
      "exclude-tags": ["20.04.1", "14.3.9"] } ]'
images:
  - name: alpine
    newName: alpine
    newTag: 3.21.2
  - name: qbittorrent
    newName: qbittorrentofficial/qbittorrent-nox
    newTag: 5.1.4-2
configMapGenerator:
  - name: qbittorrent-scripts
    files:
      - qbittorrent-scripts/qbittorrent-resume.sh
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: torrent-downloader
      app.kubernetes.io/instance: qbittorrent
      app.kubernetes.io/name: qbittorrent
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 5.1.4
secretGenerator:
  - name: qbittorrent
    envs:
      - qbittorrent/.enc.env
