---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: qbittorrent
spec:
  targetRef:
    name: qbittorrent
    apiVersion: apps/v1
    kind: StatefulSet
  updatePolicy:
    updateMode: Auto
