---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: qbittorrent-cleanup
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: qbittorrent-cleanup
            app.kubernetes.io/name: qbittorrent-cleanup
        spec:
          containers:
            - name: qbittorrent-cleanup
              image: qbittorrent-cleanup
              env:
                - name: QBT_URL
                  value: https://$(QBITTORRENT_SERVICE_HOST):$(QBITTORRENT_SERVICE_PORT)
              envFrom:
                - secretRef:
                    name: qbittorrent-cleanup
          restartPolicy: Never
  schedule: "*/2 * * * *"
