resources:
  - cronjob.yaml
images:
  - name: qbittorrent-cleanup
    newName: ghcr.io/x-shikanime/xqbit/qbittorrent-cleanup
    newTag: 4e7e1b0
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "qbittorrent-cleanup", "tag-regex": "^(?P<version>.+)$" } ]'
