apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  annotations:
    automata.shikanime.studio/images: '[ { "name": "chrome", "tag-regex": "^(?P<version>.+)$" } ]'
images:
  - name: chrome
    newName: docker.io/chromedp/headless-shell
    newTag: 149.0.7779.3
patches:
  - path: patch-sts.yaml
resources:
  - deploy.yaml
  - netpol.yaml
  - svc.yaml
