---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hermes-agent
spec:
  template:
    spec:
      enableServiceLinks: true
      containers:
        - name: hermes-agent
          env:
            - name: BROWSER_CDP_URL
              value: "ws://$(CHROME_SERVICE_HOST):$(CHROME_SERVICE_PORT)"
