---
resources:
  - ../../base
namespace: shikanime
components:
  - ../../components/api
  - ../../components/browser
  - ../../components/honcho
  - ../../components/webhook
patches:
  - path: patch-pvc.yaml
configMapGenerator:
  - name: hermes-agent-startup-config
    files:
      - hermes-agent/config.yaml
      - hermes-agent/honcho.json
      - hermes-agent/SOUL.md
secretGenerator:
  - name: hermes-agent
    envs:
      - hermes-agent/.enc.env
