apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime
configMapGenerator:
  - files:
      - hermes-agent/SOUL.md
    name: hermes-agent-startup-config
    options:
      disableNameSuffixHash: true
resources:
  - ../../base
  - ingress.yaml
  - pvc.yaml
  - proxyclass.yaml
secretGenerator:
  - envs:
      - hermes-agent/.enc.env
    name: hermes-agent
