apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime
resources:
  - ../../base
  - ingress.yaml
  - pvc.yaml
  - proxyclass.yaml
secretGenerator:
  - envs:
      - hermes-agent/.enc.env
    name: hermes-agent
