apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: automata-webhook
spec:
  statefulSet:
    pod:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: hermes-agent
              namespaces:
                - shikanime
              topologyKey: kubernetes.io/hostname
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: automata
spec:
  statefulSet:
    pod:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: hermes-agent
              namespaces:
                - shikanime
              topologyKey: kubernetes.io/hostname
