---
resources:
  - ../nishir
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: torrent-downloader
      app.kubernetes.io/instance: qbittorrent-resume
      app.kubernetes.io/name: qbittorrent-resume
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 0.0.0
