apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: flux-system
spec:
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: tailscale
        annotations:
          tailscale.com/tags: tag:web
        hosts:
          - nishir-grafana
        path: /
        pathType: Prefix
        tls: []
