apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: seerr
spec:
  statefulSet:
    pod:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: seerr
              namespaces:
                - shikanime
              topologyKey: kubernetes.io/hostname
