resources:
  - deploy.yaml
  - hpa.yaml
  - netpol.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: chrome
    newName: chromedp/headless-shell
    newTag: 149.0.7779.3
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "chrome", "tag-regex": "^(?P<version>.+)$" } ]'
