---
resources:
  - deploy.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "chrome", "tag-regex": "^(?P<version>.+)$" } ]'
images:
  - name: chrome
    newName: chromedp/headless-shell
    newTag: 149.0.7779.3
labels:
  - pairs:
      app.kubernetes.io/component: browser
      app.kubernetes.io/name: chrome
      app.kubernetes.io/part-of: nishir-platform
      app.kubernetes.io/version: 149.0.7779.3
