---
resources:
  - ingress.yaml
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
images:
  - name: mautrix
    newName: dock.mau.dev/mautrix/googlechat
    newTag: v0.5.2
  - name: rclone
    newName: rclone/rclone
    newTag: 1.71.2
configMapGenerator:
  - name: mautrix-googlechat-rclone
    namespace: shikanime
    files:
      - rclone/rclone.conf
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: communication
      app.kubernetes.io/instance: mautrix
      app.kubernetes.io/name: mautrix-googlechat
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 1.140.0
