---
apiVersion: v1
kind: Service
metadata:
  name: mautrix-googlechat
spec:
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 29320
      targetPort: http
  selector:
    app.kubernetes.io/instance: mautrix-googlechat
    app.kubernetes.io/name: mautrix-googlechat
