---
resources:
  - ../../base
patches:
  - path: patch-hr.yaml
secretGenerator:
  - name: operator-oauth
    namespace: tailscale-system
    envs:
      - operator-oauth/.enc.env
    options:
      disableNameSuffixHash: true
