---
resources:
  - ingress.yaml
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "whisparr", "tag-regex":
      "^v(?P<channel>\\d+)-(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(?:\\.(?P<build>\\d+))?$"
      }, { "name": "rclone", "tag-regex":
      "^(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)$" } ]'
images:
  - name: rclone
    newName: rclone/rclone
    newTag: 1.72.0
  - name: whisparr
    newName: ghcr.io/hotio/whisparr
    newTag: v3-3.0.2.1472
configMapGenerator:
  - name: whisparr-rclone
    namespace: shikanime
    files:
      - rclone/rclone.conf
labels:
  - pairs:
      app.kubernetes.io/component: library-manager
      app.kubernetes.io/instance: whisparr
      app.kubernetes.io/name: whisparr
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 3.0.2
