---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cluster-api
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/cluster-api/overlays/telsha
  prune: true
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cluster-api-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./configs/cluster-api/base
  prune: true
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
