resources:
  - ../nishir
  - ingress.yaml
  - netpol.yaml
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: agent
      app.kubernetes.io/instance: agentgateway
      app.kubernetes.io/name: agentgateway
      app.kubernetes.io/part-of: nishir-automata
      app.kubernetes.io/version: latest
