apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: trust-manager
  namespace: cert-manager-system
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/part-of: trust-manager
spec:
  endpoints:
    - interval: 60s
      path: /metrics
      port: metrics
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
      - cert-manager-system
  selector:
    matchLabels:
      app: trust-manager
      app.kubernetes.io/name: trust-manager
