---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: shana-control-plane
spec:
  template:
    spec:
      type: cax11
      imageName: fedora-43
      placementGroupName: control-plane
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: shana-workers
  namespace: shana
spec:
  template:
    spec:
      type: cax11
      imageName: fedora-43
      placementGroupName: workers
