---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0sControlPlane
metadata:
  name: shana
spec:
  version: v1.33.3+k0s.0
  replicas: 1
  machineTemplate:
    infrastructureRef:
      name: shana-control-plane
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: HCloudMachineTemplate
  k0sConfigSpec:
    k0s:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          port: 6443
          extraArgs:
            anonymous-auth: "true"
        network:
          kuberouter:
            extraArgs:
              advertise-cluster-ip: "true"
              advertise-external-ip: "true"
              advertise-loadbalancer-ip: "true"
