---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: shana-workers
spec:
  clusterName: shana
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: shana
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: shana
    spec:
      clusterName: shana
      bootstrap:
        configRef:
          name: shana
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
      infrastructureRef:
        name: shana-workers
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
