apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: comin-exporter
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: comin-exporter
    app.kubernetes.io/part-of: monitoring
spec:
  static_configs:
    - targets:
        - manash.taila659a.ts.net:4243
        - ashira.taila659a.ts.net:4243
        - nalsha.taila659a.ts.net:4243
        - fushi.taila659a.ts.net:4243
        - minish.taila659a.ts.net:4243
        - nemishi.taila659a.ts.net:4243
      labels:
        job: comin
        environment: production
