apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/cert-manager/base
  prune: true
  deletionPolicy: Orphan
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: flux-system
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: trust-manager
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
  interval: 10m
  path: ./configs/cert-manager/overlays/nishir
  prune: true
  deletionPolicy: Orphan
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
