---
resources:
  - ingress.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "jellyfin", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$"
      } ]'
images:
  - name: jellyfin
    newName: jellyfin/jellyfin
    newTag: 10.11.5
labels:
  - pairs:
      app.kubernetes.io/component: media-server
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 10.11.5
