---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-tailscale
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/tailscale/overlays/ishtar
  prune: true
  deletionPolicy: Orphan
  healthChecks:
    - name: operator-oauth
      apiVersion: v1
      kind: Secret
      namespace: tailscale-system
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
