apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  annotations:
    automata.shikanime.studio/images: '[ { "name": "honcho", "tag-regex": "^(?P<version>.+)$" } ]'
images:
  - name: hermes-agent-honcho
    newName: ghcr.io/plastic-labs/honcho
    newTag: latest
patches:
  - path: patch-sts.yaml
resources:
  - sts.yaml
  - svc.yaml
