apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/open-policy-agent/gatekeeper-library//library/pod-security-policy/allow-privilege-escalation?ref=b5844698218a05cc253f6c475c62bb991325fd43
  - github.com/open-policy-agent/gatekeeper-library//library/pod-security-policy/host-filesystem?ref=b5844698218a05cc253f6c475c62bb991325fd43
  - github.com/open-policy-agent/gatekeeper-library//library/pod-security-policy/host-namespaces?ref=b5844698218a05cc253f6c475c62bb991325fd43
  - github.com/open-policy-agent/gatekeeper-library//library/pod-security-policy/privileged-containers?ref=b5844698218a05cc253f6c475c62bb991325fd43
  - github.com/open-policy-agent/gatekeeper-library//library/pod-security-policy/read-only-root-filesystem?ref=b5844698218a05cc253f6c475c62bb991325fd43
  - github.com/open-policy-agent/gatekeeper-library//library/pod-security-policy/seccomp?ref=b5844698218a05cc253f6c475c62bb991325fd43
  - constraints.yaml
  - mutators.yaml
