---
apiVersion: mutations.gatekeeper.sh/v1
kind: AssignMetadata
metadata:
  name: set-ingress-allow-http-false
spec:
  location: 'metadata.annotations."kubernetes.io/ingress.allow-http"'
  match:
    kinds:
      - apiGroups:
          - networking.k8s.io
        kinds:
          - Ingress
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: "false"
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-allow-privilege-escalation-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.containers[name:*].securityContext.allowPrivilegeEscalation"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-automount-serviceaccount-token-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: spec.automountServiceAccountToken
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-capabilities-drop-all
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.containers[name:*].securityContext.capabilities.drop"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value:
        - ALL
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-enable-service-links-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: spec.enableServiceLinks
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-host-ipc-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: spec.hostIPC
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-host-network-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: spec.hostNetwork
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-host-pid-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: spec.hostPID
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-privileged-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.containers[name:*].securityContext.privileged"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-run-as-group-1000
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: spec.securityContext.runAsGroup
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: 1000
    pathTests:
      - condition: MustNotExist
        subPath: spec.securityContext.runAsGroup
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-run-as-user-1000
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: spec.securityContext.runAsUser
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: 1000
    pathTests:
      - condition: MustNotExist
        subPath: spec.securityContext.runAsUser
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-proc-mount-default-container
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.containers[name:*].securityContext.procMount"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: Default
    pathTests:
      - condition: MustNotExist
        subPath: "spec.containers[name:*].securityContext.procMount"
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-init-proc-mount-default
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.initContainers[name:*].securityContext.procMount"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: Default
    pathTests:
      - condition: MustExist
        subPath: spec.initContainers
      - condition: MustNotExist
        subPath: "spec.initContainers[name:*].securityContext.procMount"
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-ephemeral-proc-mount-default
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.ephemeralContainers[name:*].securityContext.procMount"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: Default
    pathTests:
      - condition: MustExist
        subPath: spec.ephemeralContainers
      - condition: MustNotExist
        subPath: "spec.ephemeralContainers[name:*].securityContext.procMount"
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-seccomp-profile-runtime-default-container
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.containers[name:*].securityContext.seccompProfile.type"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: RuntimeDefault
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-init-allow-privilege-escalation-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.initContainers[name:*].securityContext.allowPrivilegeEscalation"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
    pathTests:
      - condition: MustExist
        subPath: spec.initContainers
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-init-privileged-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.initContainers[name:*].securityContext.privileged"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
    pathTests:
      - condition: MustExist
        subPath: spec.initContainers
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-init-capabilities-drop-all
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.initContainers[name:*].securityContext.capabilities.drop"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value:
        - ALL
    pathTests:
      - condition: MustExist
        subPath: spec.initContainers
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-init-seccomp-profile-runtime-default
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.initContainers[name:*].securityContext.seccompProfile.type"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: RuntimeDefault
    pathTests:
      - condition: MustExist
        subPath: spec.initContainers
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-ephemeral-allow-privilege-escalation-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.ephemeralContainers[name:*].securityContext.allowPrivilegeEscalation"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
    pathTests:
      - condition: MustExist
        subPath: spec.ephemeralContainers
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-ephemeral-capabilities-drop-all
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.ephemeralContainers[name:*].securityContext.capabilities.drop"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value:
        - ALL
    pathTests:
      - condition: MustExist
        subPath: spec.ephemeralContainers
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-ephemeral-privileged-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.ephemeralContainers[name:*].securityContext.privileged"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
    pathTests:
      - condition: MustExist
        subPath: spec.ephemeralContainers
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-ephemeral-read-only-root-filesystem-true
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.ephemeralContainers[name:*].securityContext.readOnlyRootFilesystem"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: true
    pathTests:
      - condition: MustExist
        subPath: spec.ephemeralContainers
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-ephemeral-run-as-non-root-true
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.ephemeralContainers[name:*].securityContext.runAsNonRoot"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: true
    pathTests:
      - condition: MustExist
        subPath: spec.ephemeralContainers
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-ephemeral-seccomp-profile-runtime-default
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.ephemeralContainers[name:*].securityContext.seccompProfile.type"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: RuntimeDefault
    pathTests:
      - condition: MustExist
        subPath: spec.ephemeralContainers
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-init-read-only-root-filesystem-true
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.initContainers[name:*].securityContext.readOnlyRootFilesystem"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    labelSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - whisparr
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: true
    pathTests:
      - condition: MustExist
        subPath: spec.initContainers
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-init-run-emptydir-volume-mount
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: 'spec.initContainers[name:*].volumeMounts[mountPath:"/run"]'
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value:
        name: run
        mountPath: /run
    pathTests:
      - condition: MustExist
        subPath: spec.initContainers
      - condition: MustNotExist
        subPath: 'spec.initContainers[name:*].volumeMounts[mountPath:"/run"]'
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-init-tmp-emptydir-volume-mount
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: 'spec.initContainers[name:*].volumeMounts[mountPath:"/tmp"]'
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value:
        name: tmp
        mountPath: /tmp
    pathTests:
      - condition: MustExist
        subPath: spec.initContainers
      - condition: MustNotExist
        subPath: 'spec.initContainers[name:*].volumeMounts[mountPath:"/tmp"]'
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-read-only-root-filesystem-true
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.containers[name:*].securityContext.readOnlyRootFilesystem"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    labelSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - whisparr
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: true
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-run-emptydir-volume
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: spec.volumes[name:run]
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value:
        name: run
        emptyDir: {}
    pathTests:
      - condition: MustNotExist
        subPath: spec.volumes[name:run]
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-run-emptydir-volume-mount
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: 'spec.containers[name:*].volumeMounts[mountPath:"/run"]'
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value:
        name: run
        mountPath: /run
    pathTests:
      - condition: MustNotExist
        subPath: 'spec.containers[name:*].volumeMounts[mountPath:"/run"]'
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-seccomp-profile-runtime-default
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: spec.securityContext.seccompProfile.type
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: RuntimeDefault
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-tmp-emptydir-volume
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: spec.volumes[name:tmp]
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value:
        name: tmp
        emptyDir: {}
    pathTests:
      - condition: MustNotExist
        subPath: spec.volumes[name:tmp]
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-tmp-emptydir-volume-mount
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: 'spec.containers[name:*].volumeMounts[mountPath:"/tmp"]'
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value:
        name: tmp
        mountPath: /tmp
    pathTests:
      - condition: MustNotExist
        subPath: 'spec.containers[name:*].volumeMounts[mountPath:"/tmp"]'
