---
apiVersion: mutations.gatekeeper.sh/v1
kind: AssignMetadata
metadata:
  name: set-ingress-allow-http-false
spec:
  location: 'metadata.annotations."kubernetes.io/ingress.allow-http"'
  match:
    kinds:
      - apiGroups:
          - networking.k8s.io
        kinds:
          - Ingress
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: "false"
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-allow-privilege-escalation-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.containers[name:*].securityContext.allowPrivilegeEscalation"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-automount-serviceaccount-token-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: spec.automountServiceAccountToken
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-init-allow-privilege-escalation-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.initContainers[name:*].securityContext.allowPrivilegeEscalation"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: false
    pathTests:
      - condition: MustExist
        subPath: spec.initContainers
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-init-read-only-root-filesystem-true
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.initContainers[name:*].securityContext.readOnlyRootFilesystem"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: true
    pathTests:
      - condition: MustExist
        subPath: spec.initContainers
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: set-pod-read-only-root-filesystem-true
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  location: "spec.containers[name:*].securityContext.readOnlyRootFilesystem"
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  parameters:
    assign:
      value: true
