apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: pod-allow-privilege-escalation-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  location: spec.containers[name:*].securityContext.allowPrivilegeEscalation
  parameters:
    assign:
      value: false
  pathTests:
    - condition: MustNotExist
      subPath: spec.containers[name:*].securityContext.allowPrivilegeEscalation
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: pod-initcontainer-allow-privilege-escalation-false
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  location: spec.initContainers[name:*].securityContext.allowPrivilegeEscalation
  parameters:
    assign:
      value: false
  pathTests:
    - condition: MustNotExist
      subPath: spec.initContainers[name:*].securityContext.allowPrivilegeEscalation
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: pod-seccomp-runtime-default
spec:
  applyTo:
    - groups:
        - ""
      kinds:
        - Pod
      versions:
        - v1
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    namespaces:
      - shikanime
    scope: Namespaced
  location: spec.securityContext.seccompProfile.type
  parameters:
    assign:
      value: RuntimeDefault
  pathTests:
    - condition: MustNotExist
      subPath: spec.securityContext.seccompProfile.type
