resources:
  - ../../base
namespace: shikanime
components:
  - ../../components/api
  - ../../components/browser
  - ../../components/honcho
  - ../../components/webhook
patches:
  - path: patch-pvc.yaml
secretGenerator:
  - name: hermes-agent-gateway-startup-config
    envs:
      - hermes-agent-gateway/.enc.env
      - hermes-agent-gateway/config.yaml
      - hermes-agent-gateway/honcho.json
      - hermes-agent-gateway/SOUL.md
  - name: hermes-agent-gateway-ssh
    files:
      - id_ed25519=hermes-agent-gateway-ssh/id_ed25519.enc
    options:
      disableNameSuffixHash: true
