---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-bazarr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/bazarr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: bazarr
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-copyparty
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/copyparty/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: copyparty
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-forgejo
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/forgejo/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: forgejo
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-gitea-mirror
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/gitea-mirror/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: gitea-mirror
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-hermes-agent-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/hermes-agent/gateway/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: hermes-agent
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-hermes-agent-dashboard
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/hermes-agent/dashboard/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: hermes-agent
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-honcho-postgres
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/honcho-postgres/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: honcho-postgres
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-chrome
  namespace: flux-system
spec:
  dependsOn:
    - name: ifrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/chrome/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: chrome
      apiVersion: apps/v1
      kind: Deployment
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-honcho
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-honcho-postgres
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/honcho/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: honcho
      apiVersion: apps/v1
      kind: Deployment
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-jellyfin
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/jellyfin/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: jellyfin
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-lidarr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/lidarr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: lidarr
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-mautrix-discord
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/mautrix/discord/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: mautrix-discord
      apiVersion: v1
      kind: Service
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-mautrix-googlechat
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/mautrix/googlechat/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: mautrix-googlechat
      apiVersion: v1
      kind: Service
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-mautrix-linkedin
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/mautrix/linkedin/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: mautrix-linkedin
      apiVersion: v1
      kind: Service
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-mautrix-meta
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/mautrix/meta/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: mautrix-meta
      apiVersion: v1
      kind: Service
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-mautrix-signal
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/mautrix/signal/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: mautrix-signal
      apiVersion: v1
      kind: Service
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-mautrix-slack
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/mautrix/slack/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: mautrix-slack
      apiVersion: v1
      kind: Service
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-mautrix-twitter
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/mautrix/twitter/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: mautrix-twitter
      apiVersion: v1
      kind: Service
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-mautrix-whatsapp
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/mautrix/whatsapp/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: mautrix-whatsapp
      apiVersion: v1
      kind: Service
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-metatube
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/metatube/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: metatube
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-prowlarr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/prowlarr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: prowlarr
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-qbittorrent
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/qbittorrent/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: qbittorrent
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-radarr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/radarr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: radarr
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-seerr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/seerr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: seerr
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-sonarr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/sonarr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: sonarr
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-synapse
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/synapse/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: synapse
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-synapse-proxy
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/synapse-proxy/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: synapse-proxy
      apiVersion: apps/v1
      kind: Deployment
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-syncthing
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/syncthing/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: syncthing
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-vaultwarden
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/vaultwarden/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: vaultwarden
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-whisparr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-vpa
  interval: 10m
  path: ./apps/whisparr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - name: whisparr
      apiVersion: apps/v1
      kind: StatefulSet
      namespace: shikanime
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
