apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-bazarr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/bazarr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: bazarr
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-copyparty
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/copyparty/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: copyparty
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-forgejo
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/forgejo/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: forgejo
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-gitea-mirror
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/gitea-mirror/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: gitea-mirror
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-hermes-agent
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/hermes-agent/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: hermes-agent
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-jellyfin
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/jellyfin/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: jellyfin
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-lidarr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/lidarr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: lidarr
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-matrix-discord
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
  interval: 10m
  path: ./apps/mautrix/discord/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: matrix-discord
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-matrix-googlechat
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
  interval: 10m
  path: ./apps/mautrix/googlechat/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: matrix-googlechat
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-matrix-linkedin
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
  interval: 10m
  path: ./apps/mautrix/linkedin/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: matrix-linkedin
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-matrix-meta
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
  interval: 10m
  path: ./apps/mautrix/meta/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: matrix-meta
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-matrix-signal
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
  interval: 10m
  path: ./apps/mautrix/signal/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: matrix-signal
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-matrix-slack
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
  interval: 10m
  path: ./apps/mautrix/slack/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: matrix-slack
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-matrix-twitter
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
  interval: 10m
  path: ./apps/mautrix/twitter/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: matrix-twitter
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-matrix-whatsapp
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
  interval: 10m
  path: ./apps/mautrix/whatsapp/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: matrix-whatsapp
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-metatube
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-jellyfin
    - name: infrastructure-longhorn
  interval: 10m
  path: ./apps/metatube/overlays/nishir
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: metatube
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-prowlarr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/prowlarr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: prowlarr
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-qbittorrent
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/qbittorrent/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: qbittorrent
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-radarr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/radarr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: radarr
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-seerr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/seerr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: seerr
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-sonarr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/sonarr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: sonarr
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-synapse
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/synapse/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: synapse
      namespace: shikanime
    - apiVersion: apps/v1
      kind: Deployment
      name: synapse-proxy
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-syncthing
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/syncthing/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: syncthing
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-vaultwarden
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/vaultwarden/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: vaultwarden
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-whisparr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m
  path: ./apps/whisparr/overlays/nishir-tailnet
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: whisparr
      namespace: shikanime
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/cert-manager/base
  prune: true
  deletionPolicy: Orphan
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: flux-system
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: trust-manager
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-descheduler
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/descheduler/base
  prune: true
  deletionPolicy: Orphan
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: descheduler
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-flux-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-tailscale
  interval: 10m
  path: ./infrastructure/flux-operator/base
  prune: true
  deletionPolicy: Orphan
  healthChecks:
    - apiVersion: tailscale.com/v1alpha1
      kind: ProxyClass
      name: flux
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-grafana
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/grafana/overlays/nishir
  prune: true
  deletionPolicy: Orphan
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: grafana-k8s-monitoring
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-nfd
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/nfd/base
  prune: true
  deletionPolicy: Orphan
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: node-feature-discovery
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-tailscale
  interval: 10m
  path: ./infrastructure/longhorn/overlays/nishir
  prune: true
  deletionPolicy: Orphan
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: longhorn-hetzner-backups
      namespace: longhorn-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-tailscale
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/tailscale/overlays/nishir
  prune: true
  deletionPolicy: Orphan
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tailscale-operator
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-vpa
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/vpa/base
  prune: true
  deletionPolicy: Orphan
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: vpa
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
