---
resources:
  - ../../base
  - ks.yaml
components:
  - ../../components/cert-manager
  - ../../components/descheduler
  - ../../components/gatekeeper
  - ../../components/longhorn
  - ../../components/nfd
  - ../../components/tailscale
  - ../../components/vpa
patches:
  - path: patch-ingress.yaml
secretGenerator:
  - name: discord-webhook
    namespace: flux-system
    envs:
      - discord-webhook/.enc.env
  - name: receiver-token
    namespace: flux-system
    envs:
      - receiver-token/.enc.env
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: cluster
      app.kubernetes.io/instance: nishir
      app.kubernetes.io/name: nishir
      app.kubernetes.io/part-of: nishir-infrastructure
      app.kubernetes.io/version: 0.0.0
