apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/cert-manager
  - ../../components/cloudnative-pg
  - ../../components/descheduler
  - ../../components/flux-operator
  - ../../components/grafana
  - ../../components/longhorn
  - ../../components/nfd
  - ../../components/tailscale
  - ../../components/vpa
resources:
  - ../../base
  - ks.yaml
secretGenerator:
  - envs:
      - discord-webhook/.enc.env
    name: discord-webhook
    namespace: flux-system
