apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cluster-api-operator
  namespace: capi-operator-system
  labels:
    app.kubernetes.io/name: cluster-api-operator
    app.kubernetes.io/part-of: cluster-api
spec:
  endpoints:
    - interval: 60s
      path: /metrics
      port: https
      scheme: https
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
      - capi-operator-system
  selector:
    matchLabels:
      control-plane: controller-manager
