---
resources:
  - ../../base
  - ks.yaml
components:
  - ../../components/cert-manager
  - ../../components/cluster-api
  - ../../components/gatekeeper
  - ../../components/tailscale
  - ../../components/vpa
secretGenerator:
  - name: discord-webhook
    namespace: flux-system
    envs:
      - discord-webhook/.enc.env
labels:
  - pairs:
      app.kubernetes.io/component: cluster
      app.kubernetes.io/name: telsha
      app.kubernetes.io/part-of: telsha-infrastructure
      app.kubernetes.io/version: 0.0.0
