---
resources:
  - ../../base
components:
  - ../../components/cert-manager
  - ../../components/cluster-api
  - ../../components/flux-operator
  - ../../components/tailscale
  - ../../components/vpa
secretGenerator:
  - name: discord-webhook
    namespace: flux-system
    envs:
      - discord-webhook/.enc.env
