---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telsha-webhook
  namespace: flux-system
  annotations:
    tailscale.com/funnel: "true"
    tailscale.com/tags: tag:web
spec:
  ingressClassName: tailscale
