analytics:
  url: https://api.segment.io/v1/track
  token: null
  user_id: null
appservice:
  id: whatsapp
  address: http://mautrix-whatsapp:29318
  as_token: ENC[AES256_GCM,data:UYibFtAJt6855E+941eSkERlW3R6Mz+gmfYjhtSpNXTByS0Fi9D+n7vL1MzXvneYJtOBGXEGsBeHUpSppeRexw==,iv:fMduK9c/MgbkOYNl/FWzA5tcFDcAhOcr+oq94PPrSUU=,tag:i8W5xDJnDnZk4/guhtLvcg==,type:str]
  async_transactions: false
  ephemeral_events: true
  hostname: 0.0.0.0
  hs_token: ENC[AES256_GCM,data:OT3/97hxtiUtpCu1MV+y22w5D7u8Asr6YkADoJKNDJHSf2lrsk/lZTH3RQhrYhPvEAJNYrtoDr0ZUlzp8hSllA==,iv:8fNKRjKjhCoSADCQaMl4t+HLvTIRqHydBGJuAnSAXpQ=,tag:mZsVxknTAzVUycHLLRWemQ==,type:str]
  port: 29318
  public_address: https://matrix-whatsapp.taila659a.ts.net
  username_template: whatsapp_{{.}}
  bot:
    avatar: mxc://maunium.net/NeXNQarUbrlYBiPCpprYsRqr
    displayname: WhatsApp bridge bot
    username: whatsappbot
backfill:
  enabled: true
  max_catchup_messages: 500
  max_initial_messages: 50
  queue:
    batch_delay: 20
    batch_size: 100
    enabled: false
    max_batches: -1
    max_batches_override: {}
  threads:
    max_initial_messages: 50
  unread_hours_threshold: 720
bridge:
  async_events: false
  bridge_matrix_leave: false
  bridge_notices: false
  bridge_status_notices: errors
  cleanup_on_logout:
    bad_credentials:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
    enabled: false
    manual:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
  command_prefix: "!wa"
  cross_room_replies: false
  deduplicate_matrix_messages: false
  mute_only_on_create: true
  no_bridge_info_state_key: false
  only_bridge_tags:
    - m.favourite
    - m.lowpriority
  permissions:
    "*": relay
    "@root:matrix.taila659a.ts.net": admin
    matrix.taila659a.ts.net: user
  personal_filtering_spaces: true
  private_chat_portal_meta: true
  relay:
    admin_only: true
    default_relays: []
    displayname_format: "{{ .DisambiguatedName }}"
    enabled: false
    message_formats:
      m.audio:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent an audio file{{ if .Caption
        }}: {{ .Caption }}{{ end }}"
      m.emote: "* <b>{{ .Sender.DisambiguatedName }}</b> {{ .Message }}"
      m.file:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a file{{ if .Caption }}: {{
        .Caption }}{{ end }}"
      m.image:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent an image{{ if .Caption }}:
        {{ .Caption }}{{ end }}"
      m.location:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a location{{ if .Caption
        }}: {{ .Caption }}{{ end }}"
      m.notice: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.text: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.video:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a video{{ if .Caption }}:
        {{ .Caption }}{{ end }}"
  resend_bridge_info: false
  split_portals: false
  tag_only_on_create: true
  unknown_error_auto_reconnect: null
database:
  type: sqlite3-fk-wal
  max_conn_idle_time: null
  max_conn_lifetime: null
  max_idle_conns: 1
  max_open_conns: 5
  uri: file:/data/whatsapp.db?_txlock=immediate
direct_media:
  allow_proxy: true
  enabled: false
  media_id_prefix: null
  server_key: ENC[AES256_GCM,data:dqYWNxqmgcnk6ry4IXGd5+tzDeParg9i5ZNA0QncNVR8LsUqC3dZYI+SWL/N1lXqk1c56Gnn/RfDRw==,iv:xF8ialIPqVIKiD5/NnbBFCOsa1TbqI3piMIDu3sPwDE=,tag:aom9xoITvncyCj10v6lSAg==,type:str]
  server_name: matrix-discord-media.taila659a.ts.net
  well_known_response: null
double_puppet:
  allow_discovery: false
  secrets:
    matrix.taila659a.ts.net: ENC[AES256_GCM,data:XFmi/yn+qoBnu6eQ+E03kr5DiESXJYtU1CxjmYU2/KXH22bOJQF3p2Grq+F53olWb5pfWp7z4i3FDeL8fm1I8pHOa8BIk6CZtw==,iv:qVHBwgpvUrM3bOX9oHm+Y61QbEPB44mBe59ohWp2DRA=,tag:wVDoPjgBd9Gao2XihYXJKQ==,type:str]
  servers:
    anotherserver.example.org: https://matrix.anotherserver.example.org
encryption:
  allow: true
  allow_key_sharing: true
  appservice: false
  default: true
  delete_keys:
    delete_fully_used_on_decrypt: true
    delete_on_device_delete: true
    delete_outbound_on_ack: false
    delete_outdated_inbound: true
    delete_prev_on_new_session: true
    dont_store_outbound: true
    periodically_delete_expired: true
    ratchet_on_decrypt: true
  msc4190: false
  pickle_key: ENC[AES256_GCM,data:zNzk/OD58OEzVWoI+0Rqn6cSlaeDwRMsDt/4XGN4K0TVZ7BtYvuecmg3MOo1vzo6KQPsUcNowPUF9K5meI/4Tw==,iv:Re3HIujZIYFqWAOg06msWHddcGSRZMqtF7kYTmq1l4c=,tag:5zHgHRng6bDHJoK55eFatg==,type:str]
  require: false
  rotation:
    disable_device_change_key_rotation: false
    enable_custom: false
    messages: 100
    milliseconds: 6.048e+08
  self_sign: true
  verification_levels:
    receive: cross-signed-tofu
    send: cross-signed-tofu
    share: cross-signed-tofu
homeserver:
  address: https://synapse:8448
  async_media: false
  domain: matrix.taila659a.ts.net
  message_send_checkpoint_endpoint: null
  ping_interval_seconds: 0
  software: standard
  status_endpoint: null
  websocket: false
logging:
  min_level: debug
  writers:
    - type: stdout
      format: pretty-colored
    - type: file
      compress: false
      filename: ./logs/bridge.log
      format: json
      max_backups: 10
      max_size: 100
matrix:
  delivery_receipts: false
  federate_rooms: true
  message_error_notices: true
  message_status_events: false
  sync_direct_chat_list: true
  upload_file_threshold: 5.24288e+06
network:
  animated_sticker:
    args:
      fps: 25
      height: 320
      width: 320
    target: webp
  archive_tag: null
  browser_name: unknown
  call_start_notices: true
  direct_media_auto_request: true
  disable_status_broadcast_send: true
  disable_view_once: false
  displayname_template:
    '{{or .BusinessName .PushName .Phone .RedactedPhone "Unknown user"}} (WA)'
  enable_status_broadcast: true
  extev_polls: false
  force_active_delivery_receipts: false
  get_proxy_url: null
  history_sync:
    dispatch_wait: 1m
    full_sync_config:
      days_limit: null
      size_mb_limit: null
      storage_quota_mb: null
    max_initial_conversations: -1
    media_requests:
      auto_request_media: true
      max_async_handle: 2
      request_local_time: 120
      request_method: immediate
    request_full_sync: false
  identity_change_notices: false
  initial_auto_reconnect: true
  mute_status_broadcast: true
  os_name: Mautrix-WhatsApp bridge
  pinned_tag: m.favourite
  proxy: null
  proxy_only_login: false
  send_presence_on_typing: false
  status_broadcast_tag: m.lowpriority
  url_previews: false
  whatsapp_thumbnail: false
provisioning:
  allow_matrix_auth: true
  debug_endpoints: false
  enable_session_transfers: false
  shared_secret: ENC[AES256_GCM,data:+K+OLMjgUFE/Ng1/aV7OA+ou3erVQB+wI9qdzHzY+VtBQoUXlcN5Hquwu++duKz0dNGz4V4xwZ2skmqJcVFAeA==,iv:ntotbaR4Offaa6JZmbmnxsJfdfztJOBKfD+2hjUEzHA=,tag:IF9B5mJk6aK6MPhwDWBKYQ==,type:str]
public_media:
  enabled: false
  expiry: 0
  hash_length: 32
  signing_key: ENC[AES256_GCM,data:DaQiUhdDs31EL6wgQNNmRBLQhqY45lmOvX4zyhKYzTUi0YSO4tRQ1n206QFtAAMcGsESO0gvOkQaA8TJj30Kzw==,iv:Ztixhdvd/1fei9BSuuegzR1PF8IXrvgBI6iULjaISHI=,tag:vnMNYybtPhjJuGtR3/wYzA==,type:str]
sops:
  version: 3.12.2
  encrypted_regex: ^(avatar_proxy_key|as_token|hs_token|pickle_key|server_key|shared_secret|signing_key|login_shared_secret_map|secrets)$
  lastmodified: "2026-04-14T23:46:04Z"
  mac: ENC[AES256_GCM,data:nilBLpNQYQC5zbi54HJtCO1Uvt2MFQfc4VgbfDSwA5+RR5ZBjLcjLrJk6o0JaK4GdFXJrgy78ZQBeFCWB+e6ElmMdOm26wPhAL149GtUYDAXCb+ppwmfQRCImGv9voMWYS1w1MadI6ZvbV6JICWarNJQUy7qYccQtYcIxgaAHzY=,iv:Hmhno0OCQQX8jxrbb+AvjCykF8lc8La7D+JKg1HbKIY=,tag:B7mqmZOK9SqswpcfcSGxdw==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleklRWE1PS0h4OS9tNUU4
        OGlBdnJ1V0svbGRuNnB2SXpVY1BySnZQUzJRCkxuZHgyWlAyMmk3ZUEzNGtiZ1Ex
        TXJwRko4M3dNNzdlZ042dWJyTm9CcGMKLS0tIE5UcytzT1FOQ2hSUTVPckxYQ0w3
        Mzc5OEVLYXIxeWNGVG9MZ2lRSmVVSnMK3NeB/fE4V0ZcW+/prlKaoha01w752cTI
        L8XHKs6xlGKFFjPFD8wXA+vaZ/zNZbJM7dxui8GDpmgVFJJOxt6G0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZ3dvdW5iZHppS3FMdlRy
        TXVRRkEzS1NVU2gvVVl1L1ZwTmVrSFRmdjFzClUrblJKZkhnTldDS0NqcDdoQTNv
        M05DUnRndjN3aTJFMEs2S0o2Z0UzWUUKLS0tIFJyUlk3SnlYYkNkMm1mQUVmRmxm
        VFB0UkZLWHVwVWR5MzBYNmRuYnVyOHcKTZme2aQ0TmY0r6MC2TA0KxvKL1BXoyeJ
        +BNP7YUvfEyv+2otxt6TZV1GGwLX7C8RUpobIElvawGxHqVouPtR/g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NUI4S2JnbjNvMUhvMWhJ
        dmRZekFxWFFpQVEvTTB4eHBiMkFIV25hVGhVCnlEWU9pOHhUYjh6NE4zaWFJQ0oy
        TVJJQVY2eDJyNDdoTFcvMGVCNFFVRncKLS0tIDE4WnhEbjQ2MW41d2FuZ1ZiRTFW
        bWoxRGxCbTZsMDFXK3RZWXcrY1VZNHMKKtwvkDJh5M5Hzx11iauagWXvWQvLaEvr
        IuwStyp7T7irieJ5l01npBrE0/53BlDsRAVIrPEbLN+PI7d3q7SYxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
