---
resources:
  - ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: patch-hr.yaml
secretGenerator:
  - name: operator-oauth
    namespace: tailscale-system
    envs:
      - operator-oauth/.enc.env
    options:
      disableNameSuffixHash: true
