apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: nishir
spec:
  statefulSet:
    pod:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: NotIn
                    values:
                      - rpi4-model-b
                      - rpi5
              weight: 100
