apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: nishir-ca-certificates.crt
spec:
  sources:
    - secret:
        key: tls.crt
        name: nishir-ca
    - useDefaultCAs: true
  target:
    configMap:
      key: ca-certificates.crt
