---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nishir
  namespace: shikanime
spec:
  commonName: nishir
  dnsNames:
    - syncthing.taila659a.ts.net
  issuerRef:
    name: nishir
    kind: ClusterIssuer
  secretName: nishir-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nishir-ca
  namespace: cert-manager-trust
spec:
  commonName: cluster.local
  isCA: true
  issuerRef:
    name: nishir-selfsigned
    kind: ClusterIssuer
  secretName: nishir-ca
