apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: forgejo
spec:
  replicas: 1
  serviceName: forgejo
  selector:
    matchLabels:
      app.kubernetes.io/name: forgejo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: forgejo
    spec:
      initContainers:
        - name: config-sync
          image: rclone
          command:
            - rclone
          args:
            - copyto
            - --copy-links
            - --update
            - /mnt/startup-config/app.ini
            - /var/lib/gitea/custom/conf/app.ini
          volumeMounts:
            - name: data
              mountPath: /var/lib/gitea
            - name: rclone-config
              mountPath: /config/rclone/rclone.conf
              subPath: rclone.conf
              readOnly: true
            - name: config
              mountPath: /mnt/startup-config
      containers:
        - name: forgejo
          image: forgejo
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: TZ
              value: Europe/Paris
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 2222
              name: ssh
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /api/healthz
              port: http
            timeoutSeconds: 5
            failureThreshold: 180
          volumeMounts:
            - name: data
              mountPath: /var/lib/gitea
      securityContext:
        fsGroup: 1000
      volumes:
        - name: config
          secret:
            secretName: forgejo-config
        - name: rclone-config
          configMap:
            name: forgejo-rclone
        - name: data
          persistentVolumeClaim:
            claimName: forgejo-data
