---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: forgejo
spec:
  targetRef:
    name: forgejo
    apiVersion: apps/v1
    kind: StatefulSet
  updatePolicy:
    updateMode: Auto
