apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-hermes-agent-gateway
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: infrastructure-autoscaler
    - name: infrastructure-cert-manager
    - name: infrastructure-tailscale
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: hermes-agent-gateway
      namespace: shikanime
  interval: 10m
  path: ./apps/hermes-agent/gateway/overlays/talashi-tailnet
  prune: true
  sourceRef:
    name: flux-system
    kind: GitRepository
