resources:
  - ../../base
  - ks.yaml
components:
  - ../../components/autoscaler
  - ../../components/cert-manager
  - ../../components/descheduler
  - ../../components/gatekeeper
  - ../../components/longhorn
  - ../../components/monitoring
  - ../../components/tailscale
  - ../../components/tofu-controller
patches:
  - path: patch-ingress.yaml
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: cluster
      app.kubernetes.io/instance: talashi
      app.kubernetes.io/name: talashi
      app.kubernetes.io/part-of: talashi-infrastructure
      app.kubernetes.io/version: 0.0.0
secretGenerator:
  - name: discord-webhook
    namespace: flux-system
    envs:
      - discord-webhook/.enc.env
  - name: receiver-token
    namespace: flux-system
    envs:
      - receiver-token/.enc.env
