appservice:
  id: googlechat
  address: http://mautrix-googlechat:29320
  as_token: ENC[AES256_GCM,data:aiXxXfOYgmWfCdtiF9kJ3bpCy11kGnYonCPKWGZPNJU0U9xchpxYniPnAatUGLHU37khbx+oDKQ2wE626+wgzw==,iv:2kU1Ipj6qwPSMj0n4HELZBL0qZwujadwk9QclU3Q4z4=,tag:ecwkGVH58iymnQwulN4ZoQ==,type:str]
  bot_avatar: mxc://maunium.net/BDIWAQcbpPGASPUUBuEGWXnQ
  bot_displayname: Google Chat bridge bot
  bot_username: googlechatbot
  database: sqlite:/data/googlechat.db
  ephemeral_events: true
  hostname: 0.0.0.0
  hs_token: ENC[AES256_GCM,data:sk4hq4oh/hHFFf6vM7+91Td3RuSW07Z10BriVe05RgBJ6P85tG31L1CzIQ+X6hLZcq/q0n9IUbHsQVxEqbWXEg==,iv:gKfmhrqD45wpzdNydZcJhz0cYB72LiXS088GD4+fxL0=,tag:xf4kbf4kGWGFR9g0VJfLkA==,type:str]
  max_body_size: 1
  port: 29320
  database_opts:
    max_size: 10
    min_size: 1
bridge:
  backfill:
    disable_notifications: false
    initial_nonthread_limit: 100
    initial_thread_limit: 10
    initial_thread_reply_limit: 500
    invite_own_puppet: true
    missed_event_limit: 5000
    missed_event_page_size: 100
  command_prefix: "!gc"
  delivery_error_reports: true
  delivery_receipts: false
  disable_bridge_notices: false
  displayname_template: "{full_name} (Google Chat)"
  double_puppet_allow_discovery: false
  double_puppet_server_map:
    anotherserver.example.org: https://matrix.anotherserver.example.org
  encryption:
    allow: true
    allow_key_sharing: false
    appservice: false
    default: true
    delete_keys:
      delete_fully_used_on_decrypt: true
      delete_on_device_delete: true
      delete_outbound_on_ack: false
      delete_outdated_inbound: true
      delete_prev_on_new_session: true
      dont_store_outbound: true
      periodically_delete_expired: true
      ratchet_on_decrypt: true
    require: false
    rotation:
      disable_device_change_key_rotation: false
      enable_custom: false
      messages: 100
      milliseconds: 6.048e+08
    self_sign: true
    verification_levels:
      receive: cross-signed-tofu
      send: cross-signed-tofu
      share: cross-signed-tofu
  federate_rooms: true
  initial_chat_sync: 10
  invite_own_puppet_to_pm: false
  login_shared_secret_map:
    matrix.taila659a.ts.net: ENC[AES256_GCM,data:Diq+B+eFD0zFyG1RdN/93pj3kY1+bdzQGulFV8AlpbpD2/+skeNlc8/WsE168h59eVZpqwg4O1CT8eUtGn5KPw==,iv:e2Jp1i18NBwkmEHmGm+C4A+X8wLzKG3x40skH+cxcq4=,tag:Hx4h6fcxH21qys40xfnlPQ==,type:str]
  message_status_events: false
  permissions:
    "@root:matrix.taila659a.ts.net": admin
    matrix.taila659a.ts.net: user
  private_chat_portal_meta: default
  provisioning:
    prefix: /_matrix/provision
    shared_secret: ENC[AES256_GCM,data:XC9lvZVYpM6YwFBmpgpl7oKorm3IiIwYuJkBb25e2DUkxnKQ8oduZkJvGI+pdMa3j/dwjVlg3Hkbqqg+qPNrKw==,iv:fzMHK9Sttc/Q/W3KWN2JTzuGafOcEscE5DhJaj5F0XI=,tag:OSpq77htK5tzrDHRJD4sKg==,type:str]
  resend_bridge_info: false
  sync_direct_chat_list: false
  sync_with_custom_puppets: false
  unimportant_bridge_notices: false
  update_avatar_initial_sync: true
  username_template: googlechat_{userid}
homeserver:
  address: https://synapse:8448
  async_media: false
  domain: matrix.taila659a.ts.net
  http_retry_count: 4
  message_send_checkpoint_endpoint: null
  software: standard
  status_endpoint: null
  verify_ssl: true
logging:
  version: 1
  formatters:
    colored:
      (): mautrix_googlechat.util.ColorFormatter
      format: "[%(asctime)s] [%(levelname)s@%(name)s] %(message)s"
    normal:
      format: "[%(asctime)s] [%(levelname)s@%(name)s] %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: colored
  loggers:
    aiohttp:
      level: INFO
    mau:
      level: DEBUG
    maugclib:
      level: INFO
  root:
    handlers:
      - console
    level: DEBUG
manhole:
  enabled: false
  path: /var/tmp/mautrix-googlechat.manhole
  whitelist:
    - 0
metrics:
  enabled: false
  listen_port: 8000
sops:
  version: 3.12.2
  encrypted_regex: ^(avatar_proxy_key|as_token|hs_token|pickle_key|server_key|shared_secret|signing_key|login_shared_secret_map|secrets)$
  lastmodified: "2026-04-14T23:45:02Z"
  mac: ENC[AES256_GCM,data:dpE3yoKb4ojvL6cBAO7yYXvwf5xL0Tzklr78loqLQs3IExHhoEdBxEh/FUdYo06Jsu0fADz34+gk18PoYx5mHR/TUqC6a/u6Py03iEQWN3/WSblGnzqQAiJ8IhEtnsVQOt2hWPvVgakIMkyzAg0d1r0EdsqRhSK0BBQapJcwJnI=,iv:8GmsB7Di6DHCTq44l0O5SMdMLi/TjqUGicEe7pCEdaE=,tag:XlAViZb1PsTugnS3ZtHskg==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdFJyM0dDbXNoTFF5M3Ax
        eHlHMHhJMExjaDJLVkFqcjY0WW9oVEhaMFFjCnZFNTNWUGd1RjZEQy9WaWlWWEJr
        a1V5Tk1LTW1qbDc1YUdzNWM1TmdRaDAKLS0tIElha0FYTGFNYW51akRjNE91ak9y
        QXZxTEdudVZHcmxSSmZnUmxVMnZveDgKMBXu/v8ScpHu+2m8tz7RJUVLSyy4E7+c
        b2PDAmT53c9z/aOpqf6H2rX0Xyot43nDUVsK768xnM3qPB3X3H16ug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQnlmZ0ZzUzcwUUEzcDIw
        Tk9oNUwrQlVuVGdidEtqMDIyVGk4aTV3RGd3CmFCOHVtdHpRNGw5cHY1a0QwaUll
        blMzK3JueWdmTlB1S3cyOFBEcGt0SFkKLS0tIE42cTFkcFdoODdsSWxhSzhGcDAx
        UE1LWkZTMEt3M01mWGxEV09wOTdsa0UKYF/FrkC6XcCSTL0THzZLnOpQZJGJvKsX
        Y83lf/2W5If3sN09t8Cfx3tU29Z1WWAEX6Kf7T5fi1+7Bs8xwSKtaw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwS3RwbHNpZ0NOMjBJekVB
        cHFLblIzOVJYVGxKQlR2Q2g1aXN5S1pFY0RNCjhrNE5oeW44RG93NG42VTFiM2dk
        ZFY5U0xCMGQzalU4UUx6ZDhpQ3hnSjAKLS0tIHNWaGtPS2hxR1VkV003a2Y2bGVs
        MWlXbEpjN1hZOVdXRnBsMkUxT0NvWncKcHPDVzO1okd/kWoJM4myuPGQ2C/xRBie
        G1MV3DzeArCHxpE+3pVAh2MTXk4RJm7jfcfoDprZ72abLwbqMznRqg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
