---
# Homeserver details
homeserver:
  # The address that this appservice can use to connect to the homeserver.
  address: https://synapse:8448
  # The domain of the homeserver (for MXIDs, etc).
  domain: matrix.taila659a.ts.net
  # Whether or not to verify the SSL certificate of the homeserver.
  # Only applies if address starts with https://
  verify_ssl: true
  # What software is the homeserver running?
  # Standard Matrix homeservers like Synapse, Dendrite and Conduit should just use "standard" here.
  software: standard
  # Number of retries for all HTTP requests if the homeserver isn't reachable.
  http_retry_count: 4
  # The URL to push real-time bridge status to.
  # If set, the bridge will make POST requests to this URL whenever a user's Google Chat connection state changes.
  # The bridge will use the appservice as_token to authorize requests.
  status_endpoint: null
  # Endpoint for reporting per-message status.
  message_send_checkpoint_endpoint: null
  # Whether asynchronous uploads via MSC2246 should be enabled for media.
  # Requires a media repo that supports MSC2246.
  async_media: false
# Application service host/registration related details
# Changing these values requires regeneration of the registration.
appservice:
  id: googlechat
  # The address that the homeserver can use to connect to this appservice.
  address: http://mautrix-googlechat:29320
  # The hostname and port where this appservice should listen.
  hostname: 0.0.0.0
  port: 29320
  # The maximum body size of appservice API requests (from the homeserver) in mebibytes
  # Usually 1 is enough, but on high-traffic bridges you might need to increase this to avoid 413s
  max_body_size: 1
  # The full URI to the database. SQLite and Postgres are supported.
  # Format examples:
  #   SQLite:   sqlite:filename.db
  #   Postgres: postgres://username:password@hostname/dbname
  database: sqlite:/data/googlechat.db
  # Username of the appservice bot.
  bot_username: googlechatbot
  # Display name and avatar for bot. Set to "remove" to remove display name/avatar, leave empty
  # to leave display name/avatar as-is.
  bot_displayname: Google Chat bridge bot
  bot_avatar: mxc://maunium.net/BDIWAQcbpPGASPUUBuEGWXnQ
  # Whether or not to receive ephemeral events via appservice transactions.
  # Requires MSC2409 support (i.e. Synapse 1.22+).
  # You should disable bridge -> sync_with_custom_puppets when this is enabled.
  ephemeral_events: true
  # Authentication tokens for AS <-> HS communication. Autogenerated; do not modify.
  as_token: ENC[AES256_GCM,data:aiXxXfOYgmWfCdtiF9kJ3bpCy11kGnYonCPKWGZPNJU0U9xchpxYniPnAatUGLHU37khbx+oDKQ2wE626+wgzw==,iv:2kU1Ipj6qwPSMj0n4HELZBL0qZwujadwk9QclU3Q4z4=,tag:ecwkGVH58iymnQwulN4ZoQ==,type:str]
  hs_token: ENC[AES256_GCM,data:sk4hq4oh/hHFFf6vM7+91Td3RuSW07Z10BriVe05RgBJ6P85tG31L1CzIQ+X6hLZcq/q0n9IUbHsQVxEqbWXEg==,iv:gKfmhrqD45wpzdNydZcJhz0cYB72LiXS088GD4+fxL0=,tag:xf4kbf4kGWGFR9g0VJfLkA==,type:str]
  # Additional arguments for asyncpg.create_pool() or sqlite3.connect()
  # https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg.pool.create_pool
  # https://docs.python.org/3/library/sqlite3.html#sqlite3.connect
  # For sqlite, min_size is used as the connection thread pool size and max_size is ignored.
  # Additionally, SQLite supports init_commands as an array of SQL queries to run on connect (e.g. to set PRAGMAs).
  database_opts:
    min_size: 1
    max_size: 10
# Prometheus telemetry config. Requires prometheus-client to be installed.
metrics:
  enabled: false
  listen_port: 8000
# Manhole config.
manhole:
  # Whether or not opening the manhole is allowed.
  enabled: false
  # The path for the unix socket.
  path: /var/tmp/mautrix-googlechat.manhole
  # The list of UIDs who can be added to the whitelist.
  # If empty, any UIDs can be specified in the open-manhole command.
  whitelist:
    - 0
bridge:
  # Localpart template of MXIDs for Google Chat users.
  # {userid} is replaced with the user ID of the Google Chat user.
  username_template: googlechat_{userid}
  # Displayname template for Google Chat users.
  # {full_name}, {first_name}, {last_name} and {email} are replaced with names.
  displayname_template: "{full_name} (Google Chat)"
  # The prefix for commands. Only required in non-management rooms.
  command_prefix: "!gc"
  # Number of chats to sync (and create portals for) on startup/login.
  # Set 0 to disable automatic syncing.
  initial_chat_sync: 10
  # Whether or not the Google Chat users of logged in Matrix users should be
  # invited to private chats when the user sends a message from another client.
  invite_own_puppet_to_pm: false
  # Whether or not to use /sync to get presence, read receipts and typing notifications
  # when double puppeting is enabled
  sync_with_custom_puppets: false
  # Whether or not to update the m.direct account data event when double puppeting is enabled.
  # Note that updating the m.direct event is not atomic (except with mautrix-asmux)
  # and is therefore prone to race conditions.
  sync_direct_chat_list: false
  # Servers to always allow double puppeting from
  double_puppet_server_map:
    anotherserver.example.org: https://matrix.anotherserver.example.org
  double_puppet_allow_discovery: false
  # Shared secret for https://github.com/devture/matrix-synapse-shared-secret-auth
  #
  # If set, custom puppets will be enabled automatically for local users
  # instead of users having to find an access token and run `login-matrix`
  # manually.
  # If using this for other servers than the bridge's server,
  # you must also set the URL in the double_puppet_server_map.
  login_shared_secret_map:
    matrix.taila659a.ts.net: ENC[AES256_GCM,data:Diq+B+eFD0zFyG1RdN/93pj3kY1+bdzQGulFV8AlpbpD2/+skeNlc8/WsE168h59eVZpqwg4O1CT8eUtGn5KPw==,iv:e2Jp1i18NBwkmEHmGm+C4A+X8wLzKG3x40skH+cxcq4=,tag:Hx4h6fcxH21qys40xfnlPQ==,type:str]
  update_avatar_initial_sync: true
  # End-to-bridge encryption support options.
  #
  # See https://docs.mau.fi/bridges/general/end-to-bridge-encryption.html for more info.
  encryption:
    # Allow encryption, work in group chat rooms with e2ee enabled
    allow: true
    # Default to encryption, force-enable encryption in all portals the bridge creates
    # This will cause the bridge bot to be in private chats for the encryption to work properly.
    default: true
    # Whether to use MSC2409/MSC3202 instead of /sync long polling for receiving encryption-related data.
    appservice: false
    # Should the bridge bot generate a recovery key and cross-signing keys and verify itself?
    # Note that without the latest version of MSC4190, this will fail if you reset the bridge database.
    # The generated recovery key will be saved in the kv_store table under `recovery_key`.
    self_sign: true
    # Require encryption, drop any unencrypted messages.
    require: false
    # Enable key sharing? If enabled, key requests for rooms where users are in will be fulfilled.
    # You must use a client that supports requesting keys from other users to use this feature.
    allow_key_sharing: false
    # Options for deleting megolm sessions from the bridge.
    delete_keys:
      # Beeper-specific: delete outbound sessions when hungryserv confirms
      # that the user has uploaded the key to key backup.
      delete_outbound_on_ack: false
      # Don't store outbound sessions in the inbound table.
      dont_store_outbound: true
      # Ratchet megolm sessions forward after decrypting messages.
      ratchet_on_decrypt: true
      # Delete fully used keys (index >= max_messages) after decrypting messages.
      delete_fully_used_on_decrypt: true
      # Delete previous megolm sessions from same device when receiving a new one.
      delete_prev_on_new_session: true
      # Delete megolm sessions received from a device when the device is deleted.
      delete_on_device_delete: true
      # Periodically delete megolm sessions when 2x max_age has passed since receiving the session.
      periodically_delete_expired: true
      # Delete inbound megolm sessions that don't have the received_at field used for
      # automatic ratcheting and expired session deletion. This is meant as a migration
      # to delete old keys prior to the bridge update.
      delete_outdated_inbound: true
    # What level of device verification should be required from users?
    #
    # Valid levels:
    #   unverified - Send keys to all device in the room.
    #   cross-signed-untrusted - Require valid cross-signing, but trust all cross-signing keys.
    #   cross-signed-tofu - Require valid cross-signing, trust cross-signing keys on first use (and reject changes).
    #   cross-signed-verified - Require valid cross-signing, plus a valid user signature from the bridge bot.
    #                           Note that creating user signatures from the bridge bot is not currently possible.
    #   verified - Require manual per-device verification
    #              (currently only possible by modifying the `trust` column in the `crypto_device` database table).
    verification_levels:
      # Minimum level for which the bridge should send keys to when bridging messages from Telegram to Matrix.
      receive: cross-signed-tofu
      # Minimum level that the bridge should accept for incoming Matrix messages.
      send: cross-signed-tofu
      # Minimum level that the bridge should require for accepting key requests.
      share: cross-signed-tofu
    # Options for Megolm room key rotation. These options allow you to
    # configure the m.room.encryption event content. See:
    # https://spec.matrix.org/v1.3/client-server-api/#mroomencryption for
    # more information about that event.
    rotation:
      # Enable custom Megolm room key rotation settings. Note that these
      # settings will only apply to rooms created after this option is
      # set.
      enable_custom: false
      # The maximum number of milliseconds a session should be used
      # before changing it. The Matrix spec recommends 604800000 (a week)
      # as the default.
      milliseconds: 604800000
      # The maximum number of messages that should be sent with a given a
      # session before changing it. The Matrix spec recommends 100 as the
      # default.
      messages: 100
      # Disable rotating keys when a user's devices change?
      # You should not enable this option unless you understand all the implications.
      disable_device_change_key_rotation: false
  # Whether or not the bridge should send a read receipt from the bridge bot when a message has
  # been sent to Google Chat.
  delivery_receipts: false
  # Whether or not delivery errors should be reported as messages in the Matrix room.
  delivery_error_reports: true
  # Whether the bridge should send the message status as a custom com.beeper.message_send_status event.
  message_status_events: false
  # Whether or not created rooms should have federation enabled.
  # If false, created portal rooms will never be federated.
  federate_rooms: true
  # Settings for backfilling messages from Google Chat.
  backfill:
    # Whether or not the Google Chat users of logged in Matrix users should be
    # invited to private chats when backfilling history from Google Chat. This is
    # usually needed to prevent rate limits and to allow timestamp massaging.
    invite_own_puppet: true
    # Number of threads to backfill in threaded spaces in initial backfill.
    initial_thread_limit: 10
    # Number of replies to backfill in each thread in initial backfill.
    initial_thread_reply_limit: 500
    # Number of messages to backfill in non-threaded spaces and DMs in initial backfill.
    initial_nonthread_limit: 100
    # Number of events to backfill in catchup backfill.
    missed_event_limit: 5000
    # How many events to request from Google Chat at once in catchup backfill?
    missed_event_page_size: 100
    # If using double puppeting, should notifications be disabled
    # while the initial backfill is in progress?
    disable_notifications: false
  # Set this to true to tell the bridge to re-send m.bridge events to all rooms on the next run.
  # This field will automatically be changed back to false after it,
  # except if the config file is not writable.
  resend_bridge_info: false
  # Whether or not unimportant bridge notices should be sent to the bridge notice room.
  unimportant_bridge_notices: false
  # Whether or not bridge notices should be disabled entirely.
  disable_bridge_notices: false
  # Whether to explicitly set the avatar and room name for private chat portal rooms.
  # If set to `default`, this will be enabled in encrypted rooms and disabled in unencrypted rooms.
  # If set to `always`, all DM rooms will have explicit names and avatars set.
  # If set to `never`, DM rooms will never have names and avatars set.
  private_chat_portal_meta: default
  provisioning:
    # Internal prefix in the appservice web server for the login endpoints.
    prefix: /_matrix/provision
    # Shared secret for integration managers such as mautrix-manager.
    # If set to "generate", a random string will be generated on the next startup.
    # If null, integration manager access to the API will not be possible.
    shared_secret: ENC[AES256_GCM,data:XC9lvZVYpM6YwFBmpgpl7oKorm3IiIwYuJkBb25e2DUkxnKQ8oduZkJvGI+pdMa3j/dwjVlg3Hkbqqg+qPNrKw==,iv:fzMHK9Sttc/Q/W3KWN2JTzuGafOcEscE5DhJaj5F0XI=,tag:OSpq77htK5tzrDHRJD4sKg==,type:str]
  # Permissions for using the bridge.
  # Permitted values:
  #       user - Use the bridge with puppeting.
  #      admin - Use and administrate the bridge.
  # Permitted keys:
  #        * - All Matrix users
  #   domain - All users on that homeserver
  #     mxid - Specific user
  permissions:
    matrix.taila659a.ts.net: user
    "@root:matrix.taila659a.ts.net": admin
logging:
  version: 1
  formatters:
    colored:
      (): mautrix_googlechat.util.ColorFormatter
      format: "[%(asctime)s] [%(levelname)s@%(name)s] %(message)s"
    normal:
      format: "[%(asctime)s] [%(levelname)s@%(name)s] %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: colored
  loggers:
    mau:
      level: DEBUG
    maugclib:
      level: INFO
    aiohttp:
      level: INFO
  root:
    level: DEBUG
    handlers:
      - console
sops:
  version: 3.12.2
  lastmodified: "2026-04-14T23:45:02Z"
  mac: ENC[AES256_GCM,data:dpE3yoKb4ojvL6cBAO7yYXvwf5xL0Tzklr78loqLQs3IExHhoEdBxEh/FUdYo06Jsu0fADz34+gk18PoYx5mHR/TUqC6a/u6Py03iEQWN3/WSblGnzqQAiJ8IhEtnsVQOt2hWPvVgakIMkyzAg0d1r0EdsqRhSK0BBQapJcwJnI=,iv:8GmsB7Di6DHCTq44l0O5SMdMLi/TjqUGicEe7pCEdaE=,tag:XlAViZb1PsTugnS3ZtHskg==,type:str]
  encrypted_regex: ^(avatar_proxy_key|as_token|hs_token|pickle_key|server_key|shared_secret|signing_key|login_shared_secret_map|secrets)$
  age:
    - recipient: age1045knj0kzudt68plt0snrhp7u0gffp2uh8ul4g6qy93nel5rw4wq3ag2kl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZ0NzRjZlMkdtamFFSk9H
        bXRPbDlGMDE2MUJrTXBjU2ZjanRJVnAxa2dZCk1DbitQNGgvcVZoQTYvb0wwc3FG
        dWM5dzhkNDRJMU5RWlZwUkVtb00yc0kKLS0tIGt6Y1hGT0JseDZTVkUvU1FZWVNr
        OFBJbk9WMkY3WXRhUUppQWVVcmlyTE0KGl1g/LDedQunajrsacHgOUXeufS7EssN
        RJizaBbLRH5FJorKudRLOwHGvlNfG8CiI66wWxPSV39Me7tgyDd2wA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4T1ZzU2dNSWYvckpncmFx
        aHl4RXM1ejVodkNQTlRyWTZsYTQ0ZXc1M0FrClJMWVl6ZEYxZFdpcTc4b2tCeGVr
        Y1llaWpyOWE0L3B1dHRxcklzSjJvK0EKLS0tIHg0d2oybWtaVm5ZUC8rOVA4bGEy
        S1ZpUWhwUGdLU2FFRkoxTzFsZ3ptTmMKQ7OkrN48CSPlgKKPkoU5QRco1Kz12DkZ
        SYexcLv9T+LF6DCPYm5UZRvpHmxZNajiTsDTcA3C6UUR3MdLbJeYlQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dnxv9pweev9aqm5d6a8ylnw2z3tjds2hed5j73awtqmyr0cy354q068md4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNnB0OUJrUE9CWUtKbTlG
        cUdIcXFhMXNsVzQ1OVcrZEVwNHczendvaVM4CnRSbFJJOStwUmtGRmlRZldVbmsv
        eU9lbE92QlNwZDBTV2gvZFV3SlNxcEUKLS0tIGtaZ2dIYzZra2k0MW1OamlSbmJ6
        bGh5MXVBdjhGdjVGSTE5VTZlQ3FXKzQKNLHB8wZAr/Fm2RNCCjvoMbBLvvFEpaMx
        i3Rh+nxsDUg5t3Fk7knboy7bO8P5BVUaKCcd5rKtPsHAUve68s+ElA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1zwgwk8e86wz6x8vd82zwc49qtd8drpc0m6sfd46uxtvxr45ll3ws6pm6ek
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUEQ5QnN2Y0RIRkJVWlJl
        b0ZiQ0E2TXBIQnNIa3BBTnFsRHRTdHZibzNjCmVNOHF5K1hrcUMxalZUVDg0NXQ3
        U3RMRkpoanhDdllZdGxwd1B1M0NhZjAKLS0tIGZFOUhLVDI0bjkzNm10Z3kvRFA3
        eEYzN0xUN2ZucURZdkNKbS9rMFB3QWMKQbLQwOiz0i9A+Z7tLmU2QIrZzRvXJkm5
        cag48/vq1+lDbvlQGpQmHx4KkeloTBpPT8QMCPxcQYxewgh/WMn8sg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVXpBZVUxTktBbmxXSGFt
        MzdFVXNCYU83UWtlSnFwbWV0Rnh5UDZzdjE4CkFIUWk1dEhZUGhKeGtoeFM0VXFT
        cWdRblR1OEVOQUJTNG0vSE5FUXJaQncKLS0tIHZITnhyWnM2bFZYeTB5aFhpSVpu
        YVg1aUxZODV3S1N6QTJiRXkvZTZod0UKO8aedWvf4uQgccWsVBWMUR7BkwTMM0SN
        Of8V5JjkxCbiw8rqBGCXLADCyTxsk5+OmfaIX8KJw1wGVj8MYms/fg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1lcz72z6vkjywvhth955l5q9fl5wu8sdf32jpy2y6tz3rers7v5tq2gz7tx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMFo4c0VSNHVlWUd1T2Ri
        eWI1NDkwVEdTditkKzlGMy8zaXVRbXUrRHc4ClpsdjdqZG52cTdXdHBFUXlid0t6
        eFdUSjVoTnRWN1FLcjJua2ovN0tIT2sKLS0tIDZVbDBtTmhYRWExaFk2ZGYwYzRu
        c1AzMEM4VmVVSW0vRjdIS2ZFdklyV0EKKEk2OQinLuwjGjQt11TDbIXXv1o8Vk8y
        ouOAmYGHhAtfOaPmiMxXm5UigvhnBfnhyt4ZT8wYIhkXwBBQAdBi5A==
        -----END AGE ENCRYPTED FILE-----
