---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubernetes-sigs-descheduler
  namespace: flux-system
spec:
  url: https://kubernetes-sigs.github.io/descheduler
  interval: 1h
