---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: flux-system
spec:
  chart:
    spec:
      version: 0.35.1
      chart: descheduler
      interval: 1h
      sourceRef:
        name: kubernetes-sigs-descheduler
        kind: HelmRepository
        namespace: flux-system
  interval: 10m
  releaseName: descheduler
  targetNamespace: kube-system
  values:
    deschedulerPolicy:
      metricsProviders:
        - source: KubernetesMetrics
      profiles:
        - name: default
          plugins:
            deschedule:
              enabled:
                - PodLifeTime
                - RemoveFailedPods
                - RemovePodsHavingTooManyRestarts
                - RemovePodsViolatingInterPodAntiAffinity
                - RemovePodsViolatingNodeAffinity
                - RemovePodsViolatingNodeTaints
          pluginConfig:
            - name: DefaultEvictor
              args:
                podProtections:
                  extraEnabled:
                    - PodsWithPVC
                    - PodsWithResourceClaims
            - name: PodLifeTime
              args:
                maxPodLifeTimeSeconds: 3600
                states:
                  - Pending
                  - PodInitializing
            - name: RemoveFailedPods
              args:
                includingInitContainers: true
                reasons:
                  - ContainerCannotRun
                  - ContainerStatusUnknown
                  - CrashLoopBackOff
                  - CreateContainerConfigError
                  - CreateContainerError
                  - ErrImagePull
                  - Error
                  - FailedMount
                  - ImagePullBackOff
                  - RunContainerError
            - name: RemoveDuplicates
            - name: RemovePodsHavingTooManyRestarts
              args:
                includingInitContainers: true
                podRestartThreshold: 50
            - name: RemovePodsViolatingInterPodAntiAffinity
            - name: RemovePodsViolatingNodeAffinity
              args:
                nodeAffinityType:
                  - requiredDuringSchedulingIgnoredDuringExecution
            - name: RemovePodsViolatingNodeTaints
        - name: utilization
          plugins:
            balance:
              enabled:
                - LowNodeUtilization
          pluginConfig:
            - name: DefaultEvictor
            - name: LowNodeUtilization
              args:
                metricsUtilization:
                  source: KubernetesMetrics
                thresholds:
                  cpu: 10
                  memory: 10
                targetThresholds:
                  cpu: 20
                  memory: 20
                useDeviationThresholds: true
        - name: spread
          pluginConfig:
            - name: DefaultEvictor
            - name: RemoveDuplicates
            - name: RemovePodsViolatingTopologySpreadConstraint
          plugins:
            balance:
              enabled:
                - RemoveDuplicates
                - RemovePodsViolatingTopologySpreadConstraint
