---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
spec:
  template:
    spec:
      containers:
        - name: radarr
          volumeMounts:
            - name: movies-data
              mountPath: /data/movies
              subPath: Movies
            - name: movies-data
              mountPath: /downloads
              subPath: Staging
      volumes:
        - name: movies-data
          persistentVolumeClaim:
            claimName: movies-data
