apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: radarr-pkcs12-password
  namespace: shikanime
spec:
  approvePlan: auto
  interval: 30m
  path: ./modules/pkcs12-password
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  values:
    name: radarr-pkcs12-password
    namespace: shikanime
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: radarr-startup-config
  namespace: shikanime
spec:
  approvePlan: auto
  interval: 30m
  path: ./modules/radarr-config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  values:
    name: radarr
    namespace: shikanime
    passwordSecretRef:
      name: radarr-pkcs12-password
