---
resources:
  - ../nishir
  - netpol.yaml
namespace: shikanime
patches:
  - path: patch-ingress.yaml
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: library-manager
      app.kubernetes.io/instance: lidarr
      app.kubernetes.io/name: lidarr
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 3.1.0
