apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: muatrix-slack
spec:
  defaultBackend:
    service:
      name: muatrix-slack
      port:
        name: http
  tls:
    - hosts:
        - matrix-slack
