---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mautrix-slack
spec:
  replicas: 1
  serviceName: mautrix-slack
  selector:
    matchLabels:
      app.kubernetes.io/instance: mautrix-slack
      app.kubernetes.io/name: mautrix-slack
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mautrix
        app.kubernetes.io/name: mautrix-slack
    spec:
      initContainers:
        - name: config-sync
          image: rclone
          command:
            - rclone
          args:
            - copy
            - --copy-links
            - --update
            - --filter
            - "+ /config.yaml"
            - --filter
            - "+ /doublepuppet.yaml"
            - --filter
            - "+ /registration.yaml"
            - --filter
            - "- *"
            - /mnt/config
            - /mnt/data
          volumeMounts:
            - name: config
              mountPath: /mnt/config
              readOnly: true
            - name: data
              mountPath: /mnt/data
            - name: rclone-config
              mountPath: /config/rclone/rclone.conf
              subPath: rclone.conf
              readOnly: true
          securityContext:
            capabilities:
              add:
                - FOWNER
      containers:
        - name: mautrix
          image: mautrix
          ports:
            - name: http
              containerPort: 29335
          readinessProbe:
            httpGet:
              path: /_matrix/mau/ready
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 15
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /_matrix/mau/live
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 10
          startupProbe:
            httpGet:
              path: /_matrix/mau/ready
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 180
          volumeMounts:
            - name: data
              mountPath: /data
          securityContext:
            capabilities:
              add:
                - FOWNER
                - CHOWN
                - SETUID
                - SETGID
      securityContext:
        fsGroup: 1337
      volumes:
        - name: config
          secret:
            secretName: mautrix-slack
        - name: data
          persistentVolumeClaim:
            claimName: mautrix-slack-data
        - name: rclone-config
          configMap:
            name: mautrix-slack-rclone
