---
apiVersion: v1
kind: Service
metadata:
  name: mautrix-slack
spec:
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 29335
      targetPort: http
  selector:
    app.kubernetes.io/instance: mautrix-slack
    app.kubernetes.io/name: mautrix-slack
