apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: descheduler
  namespace: kube-system
  labels:
    app.kubernetes.io/name: descheduler
    app.kubernetes.io/part-of: descheduler
spec:
  endpoints:
    - interval: 60s
      path: /metrics
      port: http-metrics
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: descheduler
