---
resources:
  - deploy.yaml
  - ingress.yaml
  - netpol.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "caddy", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" } ]'
images:
  - name: caddy
    newTag: 2.11.2
