resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
components:
  - components/monitoring
images:
  - name: caddy
    newTag: 2.11.2
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "caddy", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" } ]'
