---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: synapse-proxy
spec:
  targetRef:
    name: synapse-proxy
    apiVersion: apps/v1
    kind: Deployment
  updatePolicy:
    updateMode: Auto
