analytics:
  url: https://api.segment.io/v1/track
  token: null
  user_id: null
appservice:
  id: slack
  address: http://mautrix-slack:29335
  as_token: ENC[AES256_GCM,data:ZMHax8aMjWZuaRuZLIrlsJaIrlfpnIVC+DofiJ4XEo79V5vAr6oNDexxOeFIBXbTAhDvvsMHMjYC8Cqlr8Jjnw==,iv:DKyq1Njz5mczU3DMFFnFqL2ihJxaHxI1POjDeraxH3U=,tag:yrXfb7S3dLwXp8LKsS5Ybg==,type:str]
  async_transactions: false
  ephemeral_events: true
  hostname: 0.0.0.0
  hs_token: ENC[AES256_GCM,data:/b7xNXQtKPLiYFAysfbxHt5IjyEujbXsg7XwQh9C3dhddPD0vvefVVxZ+opLLoQVkl4CPmUKJPBbf8XAeAszYw==,iv:9068fMapPC1wDZXgSlI/xzhmdcrKLYsAlSKRChB0K10=,tag:QkXtGzru4GQfYutp9eVw6w==,type:str]
  port: 29335
  public_address: https://matrix-slack-bridge.taila659a.ts.net
  username_template: slack_{{.}}
  bot:
    avatar: mxc://maunium.net/pVtzLmChZejGxLqmXtQjFxem
    displayname: Slack bridge bot
    username: slackbot
backfill:
  enabled: true
  max_catchup_messages: 500
  max_initial_messages: 50
  queue:
    batch_delay: 20
    batch_size: 100
    enabled: false
    max_batches: -1
    max_batches_override: {}
  threads:
    max_initial_messages: 50
  unread_hours_threshold: 720
bridge:
  async_events: false
  bridge_matrix_leave: false
  bridge_notices: false
  bridge_status_notices: errors
  cleanup_on_logout:
    bad_credentials:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
    enabled: false
    manual:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
  command_prefix: "!slack"
  cross_room_replies: false
  deduplicate_matrix_messages: false
  mute_only_on_create: true
  no_bridge_info_state_key: false
  only_bridge_tags:
    - m.favourite
    - m.lowpriority
  permissions:
    "*": relay
    "@root:matrix.taila659a.ts.net": admin
    matrix.taila659a.ts.net: user
  personal_filtering_spaces: true
  private_chat_portal_meta: true
  relay:
    admin_only: true
    default_relays: []
    displayname_format: "{{ .DisambiguatedName }}"
    enabled: false
    message_formats:
      m.audio:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent an audio file{{ if .Caption
        }}: {{ .Caption }}{{ end }}"
      m.emote: "* <b>{{ .Sender.DisambiguatedName }}</b> {{ .Message }}"
      m.file:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a file{{ if .Caption }}: {{
        .Caption }}{{ end }}"
      m.image:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent an image{{ if .Caption }}:
        {{ .Caption }}{{ end }}"
      m.location:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a location{{ if .Caption
        }}: {{ .Caption }}{{ end }}"
      m.notice: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.text: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.video:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a video{{ if .Caption }}:
        {{ .Caption }}{{ end }}"
  resend_bridge_info: false
  split_portals: false
  tag_only_on_create: true
  unknown_error_auto_reconnect: null
database:
  type: sqlite3-fk-wal
  max_conn_idle_time: null
  max_conn_lifetime: null
  max_idle_conns: 1
  max_open_conns: 5
  uri: file:/data/slack.db?_txlock=immediate
direct_media:
  allow_proxy: true
  enabled: false
  media_id_prefix: null
  server_key: ENC[AES256_GCM,data:kFFGoYnos0IvsY0dyxzLCJub7OjRKv2raiZhES6FcxaBybpKC3i6tUNT9Gtx6XI3NAUY8NPsJkraBQ==,iv:UhfkRdrI5m7A/eoa1OZhjDbFn3ST7i8sfbT5hYqoBPU=,tag:SE916cQQ8uLEEwSA5xBw5A==,type:str]
  server_name: matrix-discord-media.taila659a.ts.net
  well_known_response: null
double_puppet:
  allow_discovery: false
  secrets:
    matrix.taila659a.ts.net: ENC[AES256_GCM,data:XsKYV+PSNKXfEiVE25pMrQKvGtTLJWpqGEQSrnG3vR++slynSc6yM36P9RQZ5P1UGH83+lxW0Qqoe7GeceH+UbPEr5p9sddAcQ==,iv:KpahaDQHED1bNSzZn3I315DqBaDHWcP+iw4/xLpBTvc=,tag:ouEm6IMbhn97o+l0Bm6zHQ==,type:str]
  servers:
    anotherserver.example.org: https://matrix.anotherserver.example.org
encryption:
  allow: true
  allow_key_sharing: true
  appservice: false
  default: true
  delete_keys:
    delete_fully_used_on_decrypt: true
    delete_on_device_delete: true
    delete_outbound_on_ack: false
    delete_outdated_inbound: true
    delete_prev_on_new_session: true
    dont_store_outbound: true
    periodically_delete_expired: true
    ratchet_on_decrypt: true
  msc4190: false
  pickle_key: ENC[AES256_GCM,data:cph/zo/Uf5xjh/WhvJ0/d4TnoSHoDbYQ5JiP27khOxwXUvynEC5Bu6hoQs055wteiYPX5MBH1Sk/dDag6u0HuA==,iv:KR1mQ8wBiYj2fV+4lmOLCKz3L7DKOR9OXWch6weehXs=,tag:E6efCZifaETQTGhYoJsWnQ==,type:str]
  require: false
  rotation:
    disable_device_change_key_rotation: false
    enable_custom: false
    messages: 100
    milliseconds: 6.048e+08
  self_sign: true
  verification_levels:
    receive: cross-signed-tofu
    send: cross-signed-tofu
    share: cross-signed-tofu
homeserver:
  address: https://synapse:8448
  async_media: false
  domain: matrix.taila659a.ts.net
  message_send_checkpoint_endpoint: null
  ping_interval_seconds: 0
  software: standard
  status_endpoint: null
  websocket: false
logging:
  min_level: debug
  writers:
    - type: stdout
      format: pretty-colored
    - type: file
      compress: false
      filename: ./logs/bridge.log
      format: json
      max_backups: 10
      max_size: 100
matrix:
  delivery_receipts: false
  federate_rooms: true
  message_error_notices: true
  message_status_events: false
  sync_direct_chat_list: true
  upload_file_threshold: 5.24288e+06
network:
  backfill:
    conversation_count: -1
  channel_name_template:
    "{{if and .IsChannel (not .IsPrivate)}}#{{end}}{{.Name}}{{if .IsNoteToSelf}}
    (you){{end}}"
  custom_emoji_reactions: true
  displayname_template:
    "{{or .Profile.DisplayName .Profile.RealName .Name}}{{if .IsBot}}
    (bot){{end}}"
  mute_channels_by_default: false
  participant_sync_count: 5
  participant_sync_only_on_create: true
  team_name_template: "{{ .Name }}"
  workspace_avatar_in_rooms: false
provisioning:
  allow_matrix_auth: true
  debug_endpoints: false
  enable_session_transfers: false
  shared_secret: ENC[AES256_GCM,data:Q6mAkw8wyXbYPAVSPSYuQTXCKscEMlvHnCi/AnkESz9OApnsugm08nWfvQqbGDGlKffLFALzlG8VbX4T+UTwOw==,iv:RxE+Zb5j0SGzgn+WGNLlKLL75JKtJZgGvxGU/k2K0Z8=,tag:hKKv/O4IntjEj1+QCfj3xg==,type:str]
public_media:
  enabled: false
  expiry: 0
  hash_length: 32
  signing_key: ENC[AES256_GCM,data:ZY0HyXCGRdpNCXIZkt8WF/lskboZC+gL98QaH6qiF48bhyhI6B5m00O7geyibUDR1/troE4HgPEmyW0OjRZP2Q==,iv:hoCT2GCXDC0IHm6thCPNpa670lhLIK/5KyYJ8KHI6QI=,tag:crKVpgnQW3nnl4rG5afZWQ==,type:str]
sops:
  version: 3.12.2
  encrypted_regex: ^(avatar_proxy_key|as_token|hs_token|pickle_key|server_key|shared_secret|signing_key|login_shared_secret_map|secrets)$
  lastmodified: "2026-04-14T23:45:50Z"
  mac: ENC[AES256_GCM,data:mHeCGjfeT5jdpjGEK/OILAJ67gaNDmeP8pn4PtG8eQW2qoFqryyIbY/bE3aPB7l/C/+fcucYXdk0GsBEYp8Qpc5ZB4Auk8DKvVJ4K5IIJwdB/u5mZ61mkRwBHtHFAgBrdFKFZDF+iCslvAEU995yrD9joAnxKUA2Qodp2Gsf/kw=,iv:qEf0ImLkdwKkYwGFVq2k0tm2e1f8bi2YSgqttiTijqg=,tag:NzAHkTofRAiS1jRIs3FGNg==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ajhlRGdsNTg0aG9XUHRX
        QkJoRVVLRDBUL3UrYk81UnhONnFUWHMyWUVjCnlsOUNzZVRyY0JPU1dlN29qa1Ro
        NGphNFRwWHdTU2NpTHhyM3h1aTJtYVkKLS0tIHlIMHRuTkRmd09HRmhTQXJRVVB1
        eERmREUvcHk1YlJQMlhvd1lqVi9RRzgKipdwzwo49Iy3XS50Xrh1CqKlC8GR3+rJ
        tfpAdK0I4Pn/sKelOKrm1njPdE5zDwvV07PvGQnDwp3JntkofE3mXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cG5ncUp3a0laM1p0aFNj
        WGJWSXBhbUFPU2ZpcVY2Z242bHdnbjdKYWt3CjNJbndlaUo1b0RyWWdvQU1FcWpY
        Mk1UbEZUV24wbXNUVGdkdUt4T0hNaHcKLS0tIFd2bzVJQVRxNHdvamRGbmhPdkNq
        SmpiZGNOT1V1Ti9rMHVXT2d4emRJTnMKfMhPguGLK5VBhgx401u47rCoLmyHuoLc
        9tVgJL3f3vfmNyy72hWxs3FqfNKwU9UP92kB8vRJRv8Ml4k0710cSQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RUw3czVqNlFvTUhwSTk5
        QXJBV2xVS2RBMS9YM2VjaHo3WXQ0d2hBQWtRCnpQYmh5K2x5enhId29nR3F0Zmg4
        R1U3R29SRjRCZk9pU1dTVTVKd29YMzgKLS0tIGNnSkozc2hMdjYzMnZ6bHYvUElV
        REg0dTVwck0remoyUXJ2RnpYQVc5dGMKskaJ8FDCfmy6ffpA3xKw5BlhEzcbw3ID
        Hhrzgve73irElqoAI/L/dGoleNJiedyLZDAkIdoM3vI03ESu+ul1Gw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
