---
resources:
  - ../../base
  - cert.yaml
namespace: shikanime
components:
  - ../../components/ftp
  - ../../components/tls
  - ../../components/zeroconf
patches:
  - path: patch-ingress.yaml
  - path: patch-pvc.yaml
  - path: patch-sts.yaml
