apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: flux-system
spec:
  values:
    grafana:
      persistence:
        storageClassName: nishir-standard
    vmcluster:
      spec:
        vminsert:
          extraArgs:
            enableTCP6: "true"
        vmselect:
          extraArgs:
            enableTCP6: "true"
          storage:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 2Gi
                storageClassName: nishir-standard
        vmstorage:
          extraArgs:
            enableTCP6: "true"
          storage:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 8Gi
                storageClassName: nishir-standard
      enabled: true
      ingress:
        insert:
          annotations:
            tailscale.com/funnel: "true"
            tailscale.com/tags: tag:web
          enabled: true
          hosts:
            - nishir-telemetry
          ingressClassName: tailscale
          tls:
            - hosts:
                - nishir-telemetry
              secretName: vminsert-ingress-tls
    vmsingle:
      enabled: false
