---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
spec:
  template:
    spec:
      containers:
        - name: jellyfin
          volumeMounts:
            - name: movies-data
              mountPath: /data/movies
              subPath: Movies
            - name: music-data
              mountPath: /data/music
              subPath: Music
            - name: shows-data
              mountPath: /data/shows
              subPath: Shows
            - name: sukebe-data
              mountPath: /data/sukebe
              subPath: Sukebe
            - name: timeline-data
              mountPath: /data/timeline
      volumes:
        - name: movies-data
          persistentVolumeClaim:
            claimName: movies-data
        - name: music-data
          persistentVolumeClaim:
            claimName: music-data
        - name: shows-data
          persistentVolumeClaim:
            claimName: shows-data
        - name: sukebe-data
          persistentVolumeClaim:
            claimName: sukebe-data
        - name: timeline-data
          persistentVolumeClaim:
            claimName: timeline-data
