---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
spec:
  template:
    spec:
      containers:
        - name: sonarr
          volumeMounts:
            - name: shows-data
              mountPath: /data/shows
              subPath: Shows
            - name: shows-data
              mountPath: /downloads
              subPath: Staging
      volumes:
        - name: shows-data
          persistentVolumeClaim:
            claimName: shows-data
