apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix-signal
  annotations:
    tailscale.com/proxy-class: matrix-signal
    tailscale.com/tags: tag:web
spec:
  ingressClassName: tailscale
