---
resources:
  - ingress.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "vaultwarden", "tag-regex":
      "^(?P<version>\\d+\\.\\d+\\.\\d+)$", "exclude-tags": ["1.34.3"] } ]'
images:
  - name: vaultwarden
    newName: vaultwarden/server
    newTag: 1.35.4
