apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tailscale-operator
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: 1.94.2
  install:
    createNamespace: true
  interval: 10m
  releaseName: tailscale-operator
  targetNamespace: tailscale-system
  values:
    apiServerProxyConfig:
      mode: "true"
