resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
components:
  - components/monitoring
images:
  - name: mautrix
    newName: dock.mau.dev/mautrix/twitter
    newTag: v0.2604.0
  - name: rclone
    newName: rclone/rclone
    newTag: 1.74.3
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "mautrix", "tag-regex": "^v(?P<version>\\d+\\.\\d+\\.\\d+)$"
      }, { "name": "rclone", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" }
      ]'
configMapGenerator:
  - name: mautrix-twitter-rclone
    namespace: shikanime
    files:
      - rclone/rclone.conf
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: communication
      app.kubernetes.io/instance: mautrix-twitter
      app.kubernetes.io/name: mautrix-twitter
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 0.2604.0
