---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mautrix-twitter-data
spec:
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
