apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mautrix-twitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mautrix-twitter
      app.kubernetes.io/name: mautrix-twitter
  serviceName: mautrix-twitter
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mautrix-twitter
        app.kubernetes.io/name: mautrix-twitter
    spec:
      containers:
        - name: mautrix
          image: mautrix
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /_matrix/mau/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 15
          ports:
            - name: http
              containerPort: 29327
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /_matrix/mau/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 180
            httpGet:
              path: /_matrix/mau/ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - CHOWN
                - SETUID
                - SETGID
      initContainers:
        - name: config-sync
          image: rclone
          args:
            - copy
            - --copy-links
            - --filter
            - + /config.yaml
            - --filter
            - + /doublepuppet.yaml
            - --filter
            - + /registration.yaml
            - --filter
            - "- *"
            - /mnt/config
            - /mnt/data
          command:
            - rclone
          volumeMounts:
            - name: config
              mountPath: /mnt/config
              readOnly: true
            - name: data
              mountPath: /mnt/data
            - name: rclone-config
              mountPath: /config/rclone/rclone.conf
              readOnly: true
              subPath: rclone.conf
          securityContext:
            capabilities:
              add:
                - FOWNER
      securityContext:
        fsGroup: 1337
      volumes:
        - name: config
          secret:
            secretName: mautrix-twitter
        - name: data
          persistentVolumeClaim:
            claimName: mautrix-twitter-data
        - name: rclone-config
          configMap:
            name: mautrix-twitter-rclone
