apiVersion: v1
kind: Service
metadata:
  name: muatrix-twitter
spec:
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 29327
      targetPort: http
  selector:
    app.kubernetes.io/name: muatrix-twitter
