apiVersion: v1
kind: Service
metadata:
  name: mautrix-twitter
spec:
  ports:
    - name: http
      port: 29327
      targetPort: http
    - name: metrics
      port: 29327
      targetPort: http
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: mautrix-twitter
    app.kubernetes.io/name: mautrix-twitter
