---
resources:
  - ../nishir
  - netpol.yaml
  - proxyclass.yaml
namespace: shikanime
patches:
  - path: patch-ingress.yaml
secretGenerator:
  - name: mautrix-linkedin
    files:
      - config.yaml=matrix-linkedin/config.enc.yaml
      - doublepuppet.yaml=matrix-linkedin/doublepuppet.enc.yaml
      - registration.yaml=matrix-linkedin/registration.enc.yaml
    options:
      disableNameSuffixHash: true
