apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: muatrix-linkedin
  annotations:
    tailscale.com/proxy-class: muatrix-linkedin
    tailscale.com/tags: tag:web
spec:
  ingressClassName: tailscale
