apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mautrix-linkedin
  annotations:
    tailscale.com/proxy-class: mautrix-linkedin
    tailscale.com/tags: tag:web
spec:
  ingressClassName: tailscale
