apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: muatrix-googlechat
spec:
  statefulSet:
    pod:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: muatrix-googlechat
                namespaces:
                  - shikanime
                topologyKey: kubernetes.io/hostname
