apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: qbittorrent-startup-config
  namespace: shikanime
spec:
  approvePlan: auto
  interval: 30m
  path: ./modules/qbittorrent-config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  values:
    name: qbittorrent
    namespace: shikanime
