---
resources:
  - ../nishir
  - netpol.yaml
namespace: shikanime
patches:
  - path: patch-ingress.yaml
  - path: patch-sts.yaml
secretGenerator:
  - name: gitea-mirror
    envs:
      - gitea-mirror/.enc.env
