---
resources:
  - ../nishir
  - netpol.yaml
namespace: shikanime
patches:
  - path: patch-ingress.yaml
  - path: patch-sts.yaml
secretGenerator:
  - name: gitea-mirror
    envs:
      - gitea-mirror/.enc.env
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: version-control-server
      app.kubernetes.io/instance: gitea-mirror
      app.kubernetes.io/name: gitea-mirror
      app.kubernetes.io/part-of: nishir-platform
      app.kubernetes.io/version: 3.11.0
