apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: descheduler
  namespace: kube-system
  labels:
    app.kubernetes.io/name: descheduler
    app.kubernetes.io/part-of: descheduler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: descheduler
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 60s
      scrapeTimeout: 30s
