apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-tracker
  annotations:
    tailscale.com/proxy-class: qbittorrent
    tailscale.com/tags: tag:bittorrent
spec:
  loadBalancerClass: tailscale
