apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-mirror-data
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 1Gi
  storageClassName: nishir-fast
  volumeMode: Filesystem
  volumeName: gitea-mirror-data
