resources:
  - ../nishir
  - netpol.yaml
  - ingress.yaml
namespace: shikanime
patches:
  - path: patch-svc.yaml
  - path: patch-sts-oidc.yaml
secretGenerator:
  - name: forgejo-config
    files:
      - app.ini=forgejo/app.enc.ini
  - name: forgejo-oidc
    files:
      - oidc.ini=forgejo/oidc.enc.ini
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: version-control-server
      app.kubernetes.io/instance: forgejo
      app.kubernetes.io/name: forgejo
      app.kubernetes.io/part-of: nishir-platform
      app.kubernetes.io/version: 15.0.3-rootless
