---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: flux-system
spec:
  chart:
    spec:
      version: 3.8.4
      chart: k8s-monitoring
      interval: 1h
      sourceRef:
        name: grafana
        kind: HelmRepository
        namespace: flux-system
  interval: 10m
  releaseName: grafana-k8s-monitoring
  targetNamespace: grafana-system
  values:
    cluster:
      name: nishir
    destinations:
      - name: grafana-cloud-metrics
        url: https://prometheus-prod-01-eu-west-0.grafana.net./api/prom/push
        type: prometheus
        auth:
          type: basic
        secret:
          create: false
      - name: grafana-cloud-logs
        url: https://logs-prod-eu-west-0.grafana.net./loki/api/v1/push
        type: loki
        auth:
          type: basic
        secret:
          create: false
      - name: gc-otlp-endpoint
        url: https://otlp-gateway-prod-eu-west-0.grafana.net./otlp
        type: otlp
        protocol: http
        auth:
          type: basic
        secret:
          create: false
        metrics:
          enabled: true
        logs:
          enabled: true
        traces:
          enabled: true
    clusterMetrics:
      enabled: true
    clusterEvents:
      enabled: true
    podLogs:
      enabled: true
    applicationObservability:
      enabled: true
      receivers:
        otlp:
          grpc:
            enabled: true
            port: 4317
          http:
            enabled: true
            port: 4318
        zipkin:
          enabled: true
          port: 9411
    alloy-metrics:
      enabled: true
      alloy:
        extraEnv:
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: alloy-metrics-remote-cfg-grafana-k8s-monitoring
                key: password
          - name: CLUSTER_NAME
            value: nishir
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
      remoteConfig:
        url: https://fleet-management-prod-003.grafana.net
        enabled: true
        auth:
          type: basic
        secret:
          create: false
    alloy-singleton:
      enabled: true
      alloy:
        extraEnv:
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
                key: password
          - name: CLUSTER_NAME
            value: nishir
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
      remoteConfig:
        url: https://fleet-management-prod-003.grafana.net
        enabled: true
        auth:
          type: basic
        secret:
          create: false
    alloy-logs:
      enabled: true
      alloy:
        extraEnv:
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: alloy-logs-remote-cfg-grafana-k8s-monitoring
                key: password
          - name: CLUSTER_NAME
            value: nishir
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
      remoteConfig:
        url: https://fleet-management-prod-003.grafana.net
        enabled: true
        auth:
          type: basic
        secret:
          create: false
    alloy-receiver:
      enabled: true
      alloy:
        extraPorts:
          - name: otlp-grpc
            port: 4317
            targetPort: 4317
            protocol: TCP
          - name: otlp-http
            port: 4318
            targetPort: 4318
            protocol: TCP
          - name: zipkin
            port: 9411
            targetPort: 9411
            protocol: TCP
        extraEnv:
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: alloy-receiver-remote-cfg-grafana-k8s-monitoring
                key: password
          - name: CLUSTER_NAME
            value: nishir
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
      remoteConfig:
        url: https://fleet-management-prod-003.grafana.net
        enabled: true
        auth:
          type: basic
        secret:
          create: false
