apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-linkedin-data
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 512Mi
  storageClassName: nishir-fast
  volumeMode: Filesystem
  volumeName: matrix-linkedin-data
