apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - alert.yaml
  - ks.yaml
  - provider.yaml
components:
  - ../../components/longhorn
  - ../../components/nfd
  - ../../components/tls
secretGenerator:
  - envs:
      - discord-webhook/.enc.env
    name: discord-webhook
    namespace: flux-system
    options:
      disableNameSuffixHash: true
