---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: synapse-proxy-tls
spec:
  commonName: synapse
  dnsNames:
    - synapse-proxy
  issuerRef:
    name: nishir
    kind: ClusterIssuer
  secretName: synapse-proxy-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
