apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: bazarr
  namespace: shikanime
  labels:
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/part-of: bazarr
spec:
  endpoints:
    - interval: 60s
      path: /metrics
      port: http
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
      - shikanime
  selector:
    matchLabels:
      app.kubernetes.io/instance: bazarr
      app.kubernetes.io/name: bazarr