---
resources:
  - ../../base
  - netpol.yaml
namespace: shikanime
patches:
  - path: patch-pvc.yaml
  - path: patch-sts.yaml
secretGenerator:
  - name: bazarr
    files:
      - config.yaml=bazarr/config.enc.yaml
