apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vpa-tls-secret
  namespace: autoscaler-system
spec:
  commonName: vpa-admission-controller
  dnsNames:
    - vpa-admission-controller
    - vpa-admission-controller.autoscaler-system
    - vpa-admission-controller.autoscaler-system.svc
  duration: 8760h
  issuerRef:
    name: nishir
    kind: ClusterIssuer
  renewBefore: 720h
  secretName: vpa-tls-secret
  usages:
    - digital signature
    - key encipherment
    - server auth
