---
auth:
  type: basic
  apikey: ENC[AES256_GCM,data:cUWBnFiM/6Qrr+LpIY8hFjWFqh3wcm7RAM+6GnDUWmM=,iv:GMjIXmy3sbBkPukZcDrmRSu9T+qPOOFkqsESgEd0450=,tag:62fQSTWYkzDUTw2YeFpUdg==,type:str]
  password: ENC[AES256_GCM,data:tLOTfQ7jBLOp3lnhp4kQ61vCpswWLfYOf7hWd5NFaTY=,iv:w5IvS+/LWcFOVb0yPSvr2M9yNi7ocFGJJvtsT+w5maM=,tag:y+j09+RqvBf6Kwk/2AmCCg==,type:str]
  username: bazarr
log:
  exclude_filter: ""
  ignore_case: false
  include_filter: ""
  use_regex: false
napiprojekt:
  only_authors: false
  only_real_names: false
anidb:
  api_client: ""
  api_client_ver: 1
animetosho:
  anidb_api_client: ""
  anidb_api_client_ver: 1
  search_threshold: 6
anticaptcha:
  anti_captcha_key: ""
assrt:
  token: ""
avistaz:
  cookies: ""
  user_agent: ""
backup:
  day: 6
  folder: /config/backup
  frequency: Weekly
  hour: 3
  retention: 31
betaseries:
  token: ""
cinemaz:
  cookies: ""
  user_agent: ""
cors:
  enabled: true
deathbycaptcha:
  password: ""
  username: ""
embeddedsubtitles:
  fallback_lang: en
  hi_fallback: false
  included_codecs: []
  timeout: 600
  unknown_as_fallback: false
xsubs:
  password: ""
  username: ""
hdbits:
  passkey: ""
  username: ""
jimaku:
  api_key: ""
  enable_ai_subs: false
  enable_archives_download: false
  enable_name_search_fallback: true
karagarga:
  f_password: ""
  f_username: ""
  password: ""
  username: ""
movie_scores:
  source: 7
  audio_codec: 3
  edition: 1
  hash: 119
  hearing_impaired: 1
  release_group: 13
  resolution: 2
  streaming_service: 1
  title: 60
  video_codec: 2
  year: 30
legendasdivx:
  password: ""
  skip_wrong_fps: false
  username: ""
legendasnet:
  password: ""
  username: ""
analytics:
  enabled: false
addic7ed:
  cookies: ""
  password: ""
  user_agent: ""
  username: ""
  vip: false
ktuvit:
  email: ""
  hashed_password: ""
napisy24:
  password: ""
  username: ""
opensubtitles:
  password: ""
  skip_wrong_fps: false
  ssl: false
  timeout: 15
  use_tag_search: false
  username: ""
  vip: false
opensubtitlescom:
  include_ai_translated: false
  password: ""
  use_hash: true
  username: ""
plex:
  apikey: ""
  auth_method: apikey
  disable_auto_migration: false
  email: ""
  encryption_key: ENC[AES256_GCM,data:F0t+Amyz7u3eaQwjdorvdxXUSejPcK8VO3d5cT0yO8KS5B3dylnlR0ZPNw==,iv:axVENGbnyPfnvHsnXkwc85FD95EfuUXCIJz2LdghUDI=,tag:KN8gd+l5z65X4ms8orVNPQ==,type:str]
  ip: 127.0.0.1
  migration_attempted: false
  migration_successful: false
  migration_timestamp: ""
  movie_library: ""
  port: 32400
  series_library: ""
  server_local: false
  server_machine_id: ""
  server_name: ""
  server_url: ""
  set_episode_added: false
  set_movie_added: false
  ssl: false
  token: ""
  update_movie_library: false
  update_series_library: false
  user_id: ""
  username: ""
podnapisi:
  verify_ssl: true
postgresql:
  database: ""
  enabled: false
  host: localhost
  password: ""
  port: 5432
  username: ""
whisperai:
  endpoint: http://127.0.0.1:9000
  loglevel: INFO
  pass_video_name: false
  response: 5
  timeout: 3600
radarr:
  apikey: ENC[AES256_GCM,data:bAEw5Y1Pcy2jS3LKPExGF+ceEdMfBanSwrQaNg1pTAA=,iv:nj7uLmxIqGQ0g8GBLny23Nkc89W8GussqrdaJibrh0g=,tag:oGmLJqMRSwJErPxEkJ7pHA==,type:str]
  base_url: ""
  defer_search_signalr: false
  excluded_tags: []
  full_update: Daily
  full_update_day: 6
  full_update_hour: 4
  http_timeout: 60
  ip: radarr
  movies_sync: 60
  only_monitored: false
  port: 9898
  ssl: true
  sync_only_monitored_movies: false
  use_ffprobe_cache: true
series_scores:
  source: 7
  audio_codec: 3
  episode: 30
  hash: 359
  hearing_impaired: 1
  release_group: 14
  resolution: 2
  season: 30
  series: 180
  streaming_service: 1
  video_codec: 2
  year: 90
sonarr:
  apikey: ENC[AES256_GCM,data:ovRycAOx8WxbeDML017IabAdJ809v+yCvonSUmIGIlI=,iv:8gt6jVd4Det0UolUt/tpVDYmXK0z6MKMdfMK22vzGNM=,tag:Aya1p+LKZ+Gal2DIzukFBA==,type:str]
  base_url: ""
  defer_search_signalr: false
  exclude_season_zero: false
  excluded_series_types: []
  excluded_tags: []
  full_update: Daily
  full_update_day: 6
  full_update_hour: 4
  http_timeout: 60
  ip: sonarr
  only_monitored: false
  port: 9898
  series_sync: 60
  ssl: true
  sync_only_monitored_episodes: false
  sync_only_monitored_series: false
  use_ffprobe_cache: true
subdl:
  api_key: ""
subf2m:
  user_agent: ""
  verify_ssl: true
subsync:
  checker:
    blacklisted_languages: []
    blacklisted_providers: []
  debug: false
  force_audio: false
  gss: true
  max_offset_seconds: 60
  no_fix_framerate: true
  subsync_movie_threshold: 70
  subsync_threshold: 90
  use_subsync: true
  use_subsync_movie_threshold: true
  use_subsync_threshold: true
titlovi:
  password: ""
  username: ""
titulky:
  approved_only: false
  password: ""
  skip_wrong_fps: false
  username: ""
translator:
  default_score: 50
  gemini_key: ""
  gemini_model: gemini-2.0-flash
  lingarr_url: http://lingarr:9876
  translator_info: true
  translator_type: google_translate
turkcealtyaziorg:
  cookies: ""
  user_agent: ""
proxy:
  url: ""
  password: ""
  port: ""
  type: null
  username: ""
  exclude:
    - localhost
    - 127.0.0.1
general:
  adaptive_searching: true
  adaptive_searching_delay: 3w
  adaptive_searching_delta: 1w
  anti_captcha_provider: null
  auto_update: true
  base_url: ""
  branch: master
  chmod: "0640"
  chmod_enabled: false
  days_to_upgrade_subs: 30
  debug: false
  default_und_audio_lang: ""
  default_und_embedded_subtitles_lang: ""
  dont_notify_manual_actions: false
  embedded_subs_show_desired: true
  embedded_subtitles_parser: ffprobe
  enabled_integrations: []
  enabled_providers:
    - animekalesi
    - animetosho
    - embeddedsubtitles
    - gestdown
    - greeksubs
    - greeksubtitles
    - hosszupuska
    - napiprojekt
    - nekur
    - podnapisi
    - regielive
    - soustitreseu
    - subdivx
    - subssabbz
    - subs4free
    - subs4series
    - subscenter
    - subsro
    - subsunacs
    - subsynchro
    - subtitrarinoi
    - subtitriid
    - subtitulamostv
    - supersubtitles
    - titrari
    - tvsubtitles
    - wizdom
    - yavkanet
    - yifysubtitles
    - zimuku
  flask_secret_key: ENC[AES256_GCM,data:r0kW6h96pmw3OEP8TgACLs4W520krS5GRJvqqJxhHm0=,iv:j1xT2/6fa2pF7Q4AiYR1QUkkKqnHrSjyp8oIEYMRkEg=,tag:0UbXwQt8mnOUijrb5pl6sA==,type:str]
  hi_extension: hi
  ignore_ass_subs: false
  ignore_pgs_subs: false
  ignore_vobsub_subs: false
  ip: "*"
  language_equals: []
  minimum_score: 90
  minimum_score_movie: 70
  movie_default_enabled: true
  movie_default_profile: 1
  movie_tag_enabled: false
  multithreading: true
  page_size: 25
  parse_embedded_audio_track: false
  path_mappings: []
  path_mappings_movie: []
  port: 6767
  postprocessing_cmd: ""
  postprocessing_threshold: 90
  postprocessing_threshold_movie: 70
  remove_profile_tags: []
  serie_default_enabled: true
  serie_default_profile: 1
  serie_tag_enabled: false
  single_language: false
  skip_hashing: false
  subfolder: current
  subfolder_custom: ""
  subzero_mods: ""
  theme: auto
  upgrade_frequency: 12
  upgrade_manual: false
  upgrade_subs: true
  use_embedded_subs: true
  use_plex: false
  use_postprocessing: false
  use_postprocessing_threshold: false
  use_postprocessing_threshold_movie: false
  use_radarr: true
  use_scenename: true
  use_sonarr: true
  utf8_encode: true
  wanted_search_frequency: 6
  wanted_search_frequency_movie: 6
sops:
  version: 3.12.1
  lastmodified: "2026-03-17T00:26:53Z"
  mac: ENC[AES256_GCM,data:1UuUsGNGSvP/9PODygPrk60P7FoAGyAz4du8poP8MXmBglBwGX4hdxr0UHx6Xn0cH/qFyFRK5IWoznggHKcS+tfy28QzmHrkVPg7SYlpmsMPh802GabjrvLCaGbPYxP95zbHknoCZYyp7aDoN6RX665QEC6QX0BnYTegWTk6Yos=,iv:OqV5FZHW+32cuLPu0NkygpCsTDUxSsUqWmsGfkbTEAo=,tag:HBmp4UngccaHXGeRRMcr5Q==,type:str]
  encrypted_regex: ^(apikey|api_key|password|token|cookies|passkey|flask_secret_key|encryption_key|hashed_password|anti_captcha_key|gemini_key)$
  age:
    - recipient: age1045knj0kzudt68plt0snrhp7u0gffp2uh8ul4g6qy93nel5rw4wq3ag2kl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OGdTTGJNN0pVZFdIdnVU
        bCtxZzdJS2dBaWVEb2orL0p4SkFUeW5KZnlZClVvTnhjcnhNM01hNkJoSWN0VlVk
        TXFVbCtqVHNaZno5Q0VITEZoOXd3ZEUKLS0tIGVsQ1FNYUx3aitIeHdYdEoyVXRu
        czRZNjBrUWovYjNBU3VRelpLVTlWRnMKEAzDMngRygvEoRvZr1IkUsJvV/msXIUy
        qCMDLR11GJoYoaaOORLvZdV6vzQvpe5na2wVPGZHA8H+GUkRlpX8dw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5enU0QkVFc3ZRMVVRZjZX
        Z2svVXhMcHBVbTZxbEZYMVFGaUFHYThUUERvCnlodFFNNVhuckVxZE52MjQ3anFG
        U2RCT3hDRWlyS0w3VVNhRWRqcGU1eUEKLS0tIHVVTVExOEFGZytjWFpZVjVsYTl5
        eU9Tc1dnbURjWHNuOHpscUtEK1E1ZzQKHvGEvID8t9RCMhW/zzWNWKnt0IzUc4u3
        TVqn+laJSIceA40cBZA/Z0ZWnGsdW9H/qG6lu1rMznEwqI+3W7HULA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dnxv9pweev9aqm5d6a8ylnw2z3tjds2hed5j73awtqmyr0cy354q068md4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSFI5TzZ6UkVLY0RTc0Rz
        MmNXdTdva3dXdFBIN3JGWFp4c0srMUtxbTBrCjZkZ1FQaHQvTGJVWW5GYlZ6UXZv
        MHpnYXR0VUQzdncwUTNNd2p6bFc5U3MKLS0tIDZPMXRQaFFwV1c1QVpNZ2htT1N1
        MDJGTElLc09TV1VWZkc2TWFxZ3pWWTgKK++kx0SRHgCMXrU57wneQzypeiqn/WmF
        V43e4fR6ca8aMKLB6PmjU6Tywm3UJIw/nifmGYZ6kNtW6y9tbDTPWA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1a9vtmpe385n3f9nd6dxxjgcvhccc0apu22jsvwwd2d7ej82nq3tq8hwggy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eGxkMFJIanArNUdhSzJu
        SUtSVFh2UkRMQmpkOVlJc0VCNEZZTkt3dDFJCjFuZStycTRzRkZGZCtNVXBrWEo3
        NHFWdy9hdkVidHhVYU9Fc3c3VkVxbEkKLS0tIEE4ejkwRFA5SS9hTHVwcXVERExM
        VzBVK2Y2NnU1MlliZ2FubVljODB4TDAKGyiza/zlaph8I0TSB7kFHldJYwpSnfuu
        YkUp5s6Arts/tckUAHMFb5G7p+UsgILj5UNmuuZpag0K9sv+1W/bCQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQm1vRC9rU29ISWVIR2Fx
        ZUZNSVFyQ05ic1dLY1BWSlFPY0owSGxzVDI4CjVBUDlMYzZXNXR0WVV2Y1dPNXZE
        ZGIvVGpPZ2RwUE9ZNk5oT2M1ZWNZd2cKLS0tIFBoOHUveGdORHNuTVA2N0hDYlds
        UVptMmZqckVhSVkrOW9wQTAzZWZkK3MKub1/x6om7OB9HtKU3QP0zXRBOU9LsvnS
        ewZTPi/wFP90lRuDbIUbZ+/X6SnQlyHPe0F6icOWTPk3Bw/tA6aSYg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1lcz72z6vkjywvhth955l5q9fl5wu8sdf32jpy2y6tz3rers7v5tq2gz7tx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCL1o5dnBkTFc2a0ZnNS9H
        L0NzOElMTTZ5ZmhwRXBIdXVOUTZDbDRtcmlNCkpOeTdBdzJQV1pGOVptZTViVmk3
        bjNETUNxVllZUTgvQ1dQdkthSjJ2WDQKLS0tIHFTc09JQ1FkeUR4dDk3Nm5GK2NJ
        YTV4d1YxQVA2U2RBYkFhYkRYbTdVUVUKj3uYInN+40sWkpQbYKvKRh+D1L+Nukmk
        RyGuFnkYQu3RsyOtAQANRlMWM6b07HKLdSIVIDP8tK6rB1zhtDR6kQ==
        -----END AGE ENCRYPTED FILE-----
