---
apiVersion: v1
kind: Service
metadata:
  name: honcho-postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app.kubernetes.io/instance: honcho-postgres
    app.kubernetes.io/name: honcho-postgres
