---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  values:
    defaultBackupStore:
      backupTarget: s3://shikanime-studio-nishir-longhorn-backups-e9750005@fsn1/
      backupTargetCredentialSecret: longhorn-hetzner-backups
    ingress:
      host: nishir-longhorn
    persistence:
      defaultDiskSelector:
        enable: true
        selector: fast
