---
resources:
  - ingress.yaml
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "rclone", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" },
      { "name": "lidarr", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$",
      "exclude-tags": ["8.1.2135"] } ]'
images:
  - name: lidarr
    newName: lscr.io/linuxserver/lidarr
    newTag: 3.1.0
  - name: rclone
    newName: rclone/rclone
    newTag: 1.72.0
configMapGenerator:
  - name: lidarr-rclone
    namespace: shikanime
    files:
      - rclone/rclone.conf
