addic7ed:
  cookies: ""
  password: ""
  user_agent: ""
  username: ""
  vip: false
analytics:
  enabled: false
anidb:
  api_client: ""
  api_client_ver: 1
animetosho:
  anidb_api_client: ""
  anidb_api_client_ver: 1
  search_threshold: 6
anticaptcha:
  anti_captcha_key: ""
assrt:
  token: ""
auth:
  apikey: ENC[AES256_GCM,data:cUWBnFiM/6Qrr+LpIY8hFjWFqh3wcm7RAM+6GnDUWmM=,iv:GMjIXmy3sbBkPukZcDrmRSu9T+qPOOFkqsESgEd0450=,tag:62fQSTWYkzDUTw2YeFpUdg==,type:str]
  password: ENC[AES256_GCM,data:tLOTfQ7jBLOp3lnhp4kQ61vCpswWLfYOf7hWd5NFaTY=,iv:w5IvS+/LWcFOVb0yPSvr2M9yNi7ocFGJJvtsT+w5maM=,tag:y+j09+RqvBf6Kwk/2AmCCg==,type:str]
  type: basic
  username: bazarr
avistaz:
  cookies: ""
  user_agent: ""
backup:
  day: 6
  folder: /config/backup
  frequency: Weekly
  hour: 3
  retention: 31
betaseries:
  token: ""
cinemaz:
  cookies: ""
  user_agent: ""
cors:
  enabled: true
deathbycaptcha:
  password: ""
  username: ""
embeddedsubtitles:
  fallback_lang: en
  hi_fallback: false
  included_codecs: []
  timeout: 600
  unknown_as_fallback: false
general:
  adaptive_searching: true
  adaptive_searching_delay: 3w
  adaptive_searching_delta: 1w
  anti_captcha_provider: null
  auto_update: true
  base_url: ""
  branch: master
  chmod: "0640"
  chmod_enabled: false
  days_to_upgrade_subs: 30
  debug: false
  default_und_audio_lang: ""
  default_und_embedded_subtitles_lang: ""
  dont_notify_manual_actions: false
  embedded_subs_show_desired: true
  embedded_subtitles_parser: ffprobe
  enabled_integrations: []
  enabled_providers:
    - animekalesi
    - animetosho
    - embeddedsubtitles
    - gestdown
    - greeksubs
    - greeksubtitles
    - hosszupuska
    - napiprojekt
    - nekur
    - podnapisi
    - regielive
    - soustitreseu
    - subdivx
    - subssabbz
    - subs4free
    - subs4series
    - subscenter
    - subsro
    - subsunacs
    - subsynchro
    - subtitrarinoi
    - subtitriid
    - subtitulamostv
    - supersubtitles
    - titrari
    - tvsubtitles
    - wizdom
    - yavkanet
    - yifysubtitles
    - zimuku
  flask_secret_key: ENC[AES256_GCM,data:r0kW6h96pmw3OEP8TgACLs4W520krS5GRJvqqJxhHm0=,iv:j1xT2/6fa2pF7Q4AiYR1QUkkKqnHrSjyp8oIEYMRkEg=,tag:0UbXwQt8mnOUijrb5pl6sA==,type:str]
  hi_extension: hi
  ignore_ass_subs: false
  ignore_pgs_subs: false
  ignore_vobsub_subs: false
  ip: '*'
  language_equals: []
  minimum_score: 90
  minimum_score_movie: 70
  movie_default_enabled: true
  movie_default_profile: 1
  movie_tag_enabled: false
  multithreading: true
  page_size: 25
  parse_embedded_audio_track: false
  path_mappings: []
  path_mappings_movie: []
  port: 6767
  postprocessing_cmd: ""
  postprocessing_threshold: 90
  postprocessing_threshold_movie: 70
  remove_profile_tags: []
  serie_default_enabled: true
  serie_default_profile: 1
  serie_tag_enabled: false
  single_language: false
  skip_hashing: false
  subfolder: current
  subfolder_custom: ""
  subzero_mods: ""
  theme: auto
  upgrade_frequency: 12
  upgrade_manual: false
  upgrade_subs: true
  use_embedded_subs: true
  use_plex: false
  use_postprocessing: false
  use_postprocessing_threshold: false
  use_postprocessing_threshold_movie: false
  use_radarr: true
  use_scenename: true
  use_sonarr: true
  utf8_encode: true
  wanted_search_frequency: 6
  wanted_search_frequency_movie: 6
hdbits:
  passkey: ""
  username: ""
jimaku:
  api_key: ""
  enable_ai_subs: false
  enable_archives_download: false
  enable_name_search_fallback: true
karagarga:
  f_password: ""
  f_username: ""
  password: ""
  username: ""
ktuvit:
  email: ""
  hashed_password: ""
legendasdivx:
  password: ""
  skip_wrong_fps: false
  username: ""
legendasnet:
  password: ""
  username: ""
log:
  exclude_filter: ""
  ignore_case: false
  include_filter: ""
  use_regex: false
movie_scores:
  audio_codec: 3
  edition: 1
  hash: 119
  hearing_impaired: 1
  release_group: 13
  resolution: 2
  source: 7
  streaming_service: 1
  title: 60
  video_codec: 2
  year: 30
napiprojekt:
  only_authors: false
  only_real_names: false
napisy24:
  password: ""
  username: ""
opensubtitles:
  password: ""
  skip_wrong_fps: false
  ssl: false
  timeout: 15
  use_tag_search: false
  username: ""
  vip: false
opensubtitlescom:
  include_ai_translated: false
  password: ""
  use_hash: true
  username: ""
plex:
  apikey: ""
  auth_method: apikey
  disable_auto_migration: false
  email: ""
  encryption_key: ENC[AES256_GCM,data:F0t+Amyz7u3eaQwjdorvdxXUSejPcK8VO3d5cT0yO8KS5B3dylnlR0ZPNw==,iv:axVENGbnyPfnvHsnXkwc85FD95EfuUXCIJz2LdghUDI=,tag:KN8gd+l5z65X4ms8orVNPQ==,type:str]
  ip: 127.0.0.1
  migration_attempted: false
  migration_successful: false
  migration_timestamp: ""
  movie_library: ""
  port: 32400
  series_library: ""
  server_local: false
  server_machine_id: ""
  server_name: ""
  server_url: ""
  set_episode_added: false
  set_movie_added: false
  ssl: false
  token: ""
  update_movie_library: false
  update_series_library: false
  user_id: ""
  username: ""
podnapisi:
  verify_ssl: true
postgresql:
  database: ""
  enabled: false
  host: localhost
  password: ""
  port: 5432
  username: ""
proxy:
  exclude:
    - localhost
    - 127.0.0.1
  password: ""
  port: ""
  type: null
  url: ""
  username: ""
radarr:
  apikey: ENC[AES256_GCM,data:bAEw5Y1Pcy2jS3LKPExGF+ceEdMfBanSwrQaNg1pTAA=,iv:nj7uLmxIqGQ0g8GBLny23Nkc89W8GussqrdaJibrh0g=,tag:oGmLJqMRSwJErPxEkJ7pHA==,type:str]
  base_url: ""
  defer_search_signalr: false
  excluded_tags: []
  full_update: Daily
  full_update_day: 6
  full_update_hour: 4
  http_timeout: 60
  ip: radarr
  movies_sync: 60
  only_monitored: false
  port: 9898
  ssl: true
  sync_only_monitored_movies: false
  use_ffprobe_cache: true
series_scores:
  audio_codec: 3
  episode: 30
  hash: 359
  hearing_impaired: 1
  release_group: 14
  resolution: 2
  season: 30
  series: 180
  source: 7
  streaming_service: 1
  video_codec: 2
  year: 90
sonarr:
  apikey: ENC[AES256_GCM,data:ovRycAOx8WxbeDML017IabAdJ809v+yCvonSUmIGIlI=,iv:8gt6jVd4Det0UolUt/tpVDYmXK0z6MKMdfMK22vzGNM=,tag:Aya1p+LKZ+Gal2DIzukFBA==,type:str]
  base_url: ""
  defer_search_signalr: false
  exclude_season_zero: false
  excluded_series_types: []
  excluded_tags: []
  full_update: Daily
  full_update_day: 6
  full_update_hour: 4
  http_timeout: 60
  ip: sonarr
  only_monitored: false
  port: 9898
  series_sync: 60
  ssl: true
  sync_only_monitored_episodes: false
  sync_only_monitored_series: false
  use_ffprobe_cache: true
subdl:
  api_key: ""
subf2m:
  user_agent: ""
  verify_ssl: true
subsync:
  checker:
    blacklisted_languages: []
    blacklisted_providers: []
  debug: false
  force_audio: false
  gss: true
  max_offset_seconds: 60
  no_fix_framerate: true
  subsync_movie_threshold: 70
  subsync_threshold: 90
  use_subsync: true
  use_subsync_movie_threshold: true
  use_subsync_threshold: true
titlovi:
  password: ""
  username: ""
titulky:
  approved_only: false
  password: ""
  skip_wrong_fps: false
  username: ""
translator:
  default_score: 50
  gemini_key: ""
  gemini_model: gemini-2.0-flash
  lingarr_url: http://lingarr:9876
  translator_info: true
  translator_type: google_translate
turkcealtyaziorg:
  cookies: ""
  user_agent: ""
whisperai:
  endpoint: http://127.0.0.1:9000
  loglevel: INFO
  pass_video_name: false
  response: 5
  timeout: 3600
xsubs:
  password: ""
  username: ""
sops:
  age:
    - recipient: age1045knj0kzudt68plt0snrhp7u0gffp2uh8ul4g6qy93nel5rw4wq3ag2kl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdUFCMXc0MjArWGJhYXN0
        aCt1TVZjaXF5bWtvRit1eStRVmdRUEdlZ1NnCnh2MFlGcFlQalBURThNcWk0WWpp
        TVplMzE5TVhxck9nS25oS1l4ZURDNEEKLS0tIHBFaklHYXdRS2VkbXZiQWg1aGRw
        ZW90YU9qL0YvNGorVjVnTitvYjFUejgK0/WJWfuiVhjdJy0nxt8vxheD7R5r0TPB
        9CFqAy0XbLdSfOU2WEGkKCMD/G6WIGxrCOtOwx4KC9FT3aRJGFDT9Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhazIvVjYrcUc1UWlRTWJz
        Zkh3cEZvUElRYkNvVzFTT2Y5ZitHdXh3K2l3ClQzR1o4ZHZsTDBDMzNRNjNEUU9Q
        dWpqVkxqVGNTeUQ5WERqai80RXdmWkEKLS0tIGhKcGJVVFFiME9lTGQ2TmJFWWlC
        SFpLaWJKQUhDZVdxUGJpTzgybmFpOGcKVEWSKf6mrIKxgX1FkKQDyuaoZibDX0/z
        nfiGSAsdRWIPMWcZv6VwDGa4fx9DBCyOyS3IrEUmzCdXmejuTZSk5g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dnxv9pweev9aqm5d6a8ylnw2z3tjds2hed5j73awtqmyr0cy354q068md4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dkNSejdhc1l6NVJYekh2
        MDI2d3RaODZ5TXEzdkNyVURXbFlQWk5aQndnCkh5ZWFhclNuYWxjNFZnb3hONHJl
        VmFFVDZtVGl4RUtrMlJtOHpUWkJpblEKLS0tIHlJU0p6OVhOYld4VmR2TUI2aHBD
        K3pXdXVFVlEzYmZZVTZzM1Ara1NMUW8KoS6Eqs7x/hUubOnDWTZX4QUh5SpXTip5
        DWYlBV8jzd/r0PgntHZevjQtGSwTILKpqDsRHW56Fv8zbgpZntE9EA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17pepaj2fgfsh5a0nzdhjsylv8qdstffmapy5xwvymjh5s9wz8uaqgvzdvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSS3Y3RTFFUVNIYmZrN1FG
        UEVScFBRMXpPbEZuVXVCbFdvbG5TSFdDdTN3CjU0WVpWWkY5UjdFeUEyWURHZXdN
        eldkSy82WXdHOUFUaHBlRTc1c1B3T2cKLS0tIEFrbTNYVFlGYmNqMTlmRnlmUEg1
        Yk1XVjM0Ujd1VHVmMVNrVzNJRlpIcDgK99vqU4li0O04KUvAYMOPvaHWy8nM/Y3t
        hFgoLK0iErqMTY6eWNz8otQJyVLERiBVIi0tC4fAp4K5YOf7fgoxdQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUnp3U01uVXQwcTJpdzNO
        V09Tb1J5VXA4bGExaDFzK1k4bVdvTVQ4SzAwClZydGQ0UW02NEpZSDkzaUNiTG1v
        NHNRbmI2QUxmMFVjL0U4cFA5dnpaYVkKLS0tIFVZWElWbHArTzlVWHlZb0FXNkNL
        UVJEc3UwSjhMaEpwcjd6Q3h4dkNqUjQKcAl40G9kprt/faJMoHOwIQMCihS18+O1
        iyj6DY2MIocYDBrfMKd2HszPaADpu+rvYBvylQ13+1BGKtu7xpVytA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T00:26:53Z"
  mac: ENC[AES256_GCM,data:1UuUsGNGSvP/9PODygPrk60P7FoAGyAz4du8poP8MXmBglBwGX4hdxr0UHx6Xn0cH/qFyFRK5IWoznggHKcS+tfy28QzmHrkVPg7SYlpmsMPh802GabjrvLCaGbPYxP95zbHknoCZYyp7aDoN6RX665QEC6QX0BnYTegWTk6Yos=,iv:OqV5FZHW+32cuLPu0NkygpCsTDUxSsUqWmsGfkbTEAo=,tag:HBmp4UngccaHXGeRRMcr5Q==,type:str]
  encrypted_regex: ^(apikey|api_key|password|token|cookies|passkey|flask_secret_key|encryption_key|hashed_password|anti_captcha_key|gemini_key)$
  version: 3.12.1
