apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: agentgateway
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agentgateway
  updatePolicy:
    updateMode: Auto
