apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-gatekeeper
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  deletionPolicy: Orphan
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: gatekeeper
      namespace: flux-system
  interval: 10m
  path: ./infrastructure/gatekeeper/overlays/talashi
  timeout: 20m
  prune: true
  sourceRef:
    name: flux-system
    kind: GitRepository
