---
resources:
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "catbox", "tag-regex": "^(?P<version>\\d+\\.\\d+)$" } ]'
images:
  - name: catbox
    newName: qemux/qemu
    newTag: "7.29"
labels:
  - pairs:
      app.kubernetes.io/component: backend-service
      app.kubernetes.io/name: catbox
      app.kubernetes.io/part-of: telsha-workstation
      app.kubernetes.io/version: "7.29"
