---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catbox
  serviceName: catbox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catbox
    spec:
      securityContext:
        fsGroup: 100
      containers:
        - name: catbox
          image: catbox
          stdin: true
          tty: true
          env:
            - name: BOOT
              value: nixos
          ports:
            - name: ssh
              containerPort: 22
            - name: mdns
              containerPort: 5353
              protocol: UDP
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: ssh
            timeoutSeconds: 5
          readinessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: ssh
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 180
            initialDelaySeconds: 3
            tcpSocket:
              port: ssh
            timeoutSeconds: 5
          volumeMounts:
            - name: catbox-data
              mountPath: /storage
          volumeDevices:
            - name: kvm
              mountPath: /dev/kvm
            - name: tun
              mountPath: /dev/net/tun
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: catbox-data
          persistentVolumeClaim:
            claimName: catbox-storage
        - name: kvm
          type: CharDevice
          hostPath:
            path: /dev/kvm
        - name: tun
          type: CharDevice
          hostPath:
            path: /dev/net/tun
