---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hermes-agent
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: hermes-agent
      app.kubernetes.io/name: hermes-agent
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: hermes-agent-dashboard
      ports:
        - port: http
