resources:
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: syncthing
    newName: syncthing/syncthing
    newTag: 2.1.1
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "syncthing", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$"
      } ]'
