---
resources:
  - ingress.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "syncthing", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$"
      } ]'
images:
  - name: syncthing
    newName: syncthing/syncthing
    newTag: 2.0.12
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: file-synchronizer
      app.kubernetes.io/instance: syncthing
      app.kubernetes.io/name: syncthing
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 2.0.12
