apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-mirror
spec:
  defaultBackend:
    service:
      name: gitea-mirror
      port:
        name: http
  tls:
    - hosts:
        - gitea-mirror
