apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seerr
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - rpi5-large
                      - rpi4-large
              weight: 80
