---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix-discord
spec:
  defaultBackend:
    service:
      name: mautrix-discord
      port:
        name: http
  tls:
    - hosts:
        - matrix-discord
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix-discord-media
spec:
  defaultBackend:
    service:
      name: synapse-proxy
      port:
        name: http
  tls:
    - hosts:
        - matrix-discord-media
