apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix-whatsapp
spec:
  defaultBackend:
    service:
      name: matrix-whatsapp
      port:
        name: http
  tls:
    - hosts:
        - matrix-whatsapp
