apiVersion: v1
kind: Service
metadata:
  name: mautrix-whatsapp
spec:
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 29318
      targetPort: http
  selector:
    app.kubernetes.io/name: mautrix-whatsapp
