apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-vpa
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
  interval: 10m
  path: ./infrastructure/vpa/overlays/telsha
  prune: true
  sourceRef:
    name: flux-system
    kind: GitRepository
  decryption:
    provider: sops
    secretRef:
      name: sops-age
