apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: matrix-discord-tailscale
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: matrix-discord
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: tailscale-system
      ports:
        - port: http
