apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mautrix-discord
  annotations:
    tailscale.com/proxy-class: mautrix-discord
    tailscale.com/tags: tag:web
spec:
  ingressClassName: tailscale
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mautrix-discord-media
  annotations:
    tailscale.com/funnel: "true"
    tailscale.com/proxy-class: synapse
    tailscale.com/tags: tag:web
spec:
  ingressClassName: tailscale
