apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: forgejo-tailscale
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: forgejo
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: tailscale-system
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gitea-mirror
      ports:
        - port: http
        - port: ssh
