[global]
  # System settings
  ansi
  hist: /cfg/hists/
  name: copyparty
  no-fpool
  no-robots
  shr: /share

  # 4MB buffer for file transfers
  iobuf: 4194304

  # Auto-detect number of CPU cores for jobs
  j: 0

  # Auth
  ah-alg: argon2
  dav-auth
  idp-h-usr: Tailscale-User-Login

  # Reverse Proxy
  rproxy: 1
  xff-hdr: x-forwarded-for
  xff-src: 127.0.0.1, 169.254.0.0/16, 10.244.0.0/16

  # Network access
  ipar: 127.0.0.1, 169.254.0.0/16, 100.64.0.0/10, 172.16.0.0/12, 192.168.0.0/16, 10.0.0.0/8

  # FTP/SFTP settings
  ftp: 3921
  ftps: 3990
  ftp-nat: 100.68.52.27
  ftp-pr: 12000-12099
  sftp: 3922
  sftp-pw
  sftp-key: shikanime.deva@gmail.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH+tp1Xfz7NomHCZuDPlfj3XW5hm9t0TiCyEeudRraoe

[accounts]
  shikanime.deva@gmail.com: +WET08bmiXqz4TUCIVXXaqNxF49JyX_ul
  shikalegend@gmail.com: +sgV1GQKTRSLwZofWsVij1G8I5pcPYCv_

[groups]
  users: shikanime.deva@gmail.com
  admins: shikalegend@gmail.com

[/]
  /data
  accs:
    r: @users
    ra.: @admins

[/archives]
  /data/archives
  accs:
    rwmd: @users
    rwmda.: @admins
  flags:
    e2dsa
    e2ts

[/downloads]
  /data/downloads
  accs:
    rwmd: @users
    rwmda.: @admins

[/movies]
  /data/movies
  accs:
    rwmd: @users
    rwmda.: @admins
  flags:
    e2dsa
    e2ts

[/music]
  /data/music
  accs:
    r: @users
    rwmda.: @admins
  flags:
    e2dsa
    e2ts

[/shows]
  /data/shows
  accs:
    rwmd: @users
    rwmda.: @admins
  flags:
    e2dsa
    e2ts

[/staging]
  /data/staging
  accs:
    r: @users
    rwmda.: @admins

[/sukebe]
  /data/sukebe
  accs:
    rwmd: @users
    rwmda.: @admins
  flags:
    e2dsa
    e2ts

[/sync]
  /data/sync
  accs:
    r: @users
    rwmda.: @admins
  flags:
    e2dsa
    e2ts

[/timeline]
  /data/timeline
  accs:
    r: @users
    rwmda.: @admins
  flags:
    e2dsa
    e2ts
