apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chrome
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chrome
    spec:
      containers:
        - name: chrome
          image: chrome
          ports:
            - containerPort: 9222
              name: cdp
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: chrome
spec:
  ports:
    - name: cdp
      port: 9222
      targetPort: cdp
  selector:
    app.kubernetes.io/name: chrome
