---
resources:
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "hermes-agent", "tag-regex": "^(?P<version>.+)$" } ]'
images:
  - name: rclone
    newName: rclone/rclone
    newTag: 1.71.2
  - name: hermes-agent
    newName: nousresearch/hermes-agent
    newTag: v2026.4.16
configMapGenerator:
  - name: hermes-agent-rclone
    files:
      - rclone/rclone.conf
secretGenerator:
  - name: hermes-agent-ssh
    files:
      - id_ed25519=hermes-agent/id_ed25519.enc
    options:
      disableNameSuffixHash: true
