apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hermes-agent
spec:
  replicas: 1
  serviceName: hermes-agent
  selector:
    matchLabels:
      app.kubernetes.io/name: hermes-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hermes-agent
    spec:
      initContainers:
        - name: config-sync
          image: rclone
          command:
            - rclone
          args:
            - copy
            - --copy-links
            - --update
            - --include
            - SOUL.md
            - --include
            - config.yaml
            - --exclude
            - "*"
            - /mnt/startup-config
            - /opt/data
          volumeMounts:
            - name: data
              mountPath: /opt/data
            - name: startup-config
              mountPath: /mnt/startup-config
              readOnly: true
        - name: hermes-setup
          image: hermes-agent
          args:
            - setup
            - --non-interactive
          envFrom:
            - secretRef:
                name: hermes-agent
          volumeMounts:
            - name: data
              mountPath: /opt/data
      containers:
        - name: hermes-agent
          image: hermes-agent
          args:
            - gateway
            - run
          env:
            - name: BROWSER_CDP_URL
              value: "ws://chrome:3000"
            - name: DISCORD_ALLOW_BOTS
              value: "mentions"
            - name: DISCORD_REACTIONS
              value: "false"
          envFrom:
            - secretRef:
                name: hermes-agent
          volumeMounts:
            - name: data
              mountPath: /opt/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hermes-agent-data
        - name: startup-config
          configMap:
            name: hermes-agent-startup-config
