---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hermes-agent
spec:
  replicas: 1
  serviceName: hermes-agent
  selector:
    matchLabels:
      app.kubernetes.io/instance: hermes-agent
      app.kubernetes.io/name: hermes-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hermes-agent
        app.kubernetes.io/name: hermes-agent
    spec:
      initContainers:
        - name: config-sync
          image: rclone
          command:
            - rclone
          args:
            - copy
            - --copy-links
            - --no-modtime
            - --update
            - --filter
            - "+ /config.yaml"
            - --filter
            - "+ /honcho.json"
            - --filter
            - "+ /SOUL.md"
            - --filter
            - "- *"
            - /mnt/startup-config
            - /opt/data
          securityContext:
            runAsUser: 10000
            runAsGroup: 10000
          volumeMounts:
            - name: data
              mountPath: /opt/data
            - name: rclone-config
              mountPath: /config/rclone/rclone.conf
              subPath: rclone.conf
              readOnly: true
            - name: startup-config
              mountPath: /mnt/startup-config
              readOnly: true
        - name: hermes-setup
          image: hermes-agent
          args:
            - setup
            - --non-interactive
          securityContext:
            runAsUser: 10000
            runAsGroup: 10000
          volumeMounts:
            - name: data
              mountPath: /opt/data
            - name: rclone-config
              mountPath: /config/rclone/rclone.conf
              subPath: rclone.conf
              readOnly: true
            - name: ssh-key
              mountPath: /root/.ssh
              readOnly: true
          envFrom:
            - secretRef:
                name: hermes-agent
      containers:
        - name: hermes-agent
          image: hermes-agent
          args:
            - gateway
            - run
          env:
            - name: DISCORD_ALLOW_BOTS
              value: "mentions"
          volumeMounts:
            - name: data
              mountPath: /opt/data
            - name: rclone-config
              mountPath: /config/rclone/rclone.conf
              subPath: rclone.conf
              readOnly: true
            - name: ssh-key
              mountPath: /root/.ssh
              readOnly: true
          envFrom:
            - secretRef:
                name: hermes-agent
      securityContext:
        fsGroup: 10000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hermes-agent-data
        - name: rclone-config
          configMap:
            name: hermes-agent-rclone
        - name: startup-config
          configMap:
            name: hermes-agent-startup-config
        - name: ssh-key
          secret:
            secretName: hermes-agent-ssh
            defaultMode: 0400
