apiVersion: v1
kind: Service
metadata:
  name: chrome
spec:
  ports:
    - name: cdp
      port: 9222
      targetPort: cdp
  selector:
    app.kubernetes.io/name: chrome
---
apiVersion: v1
kind: Service
metadata:
  name: hermes-agent
spec:
  selector:
    app.kubernetes.io/name: hermes-agent
