apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix
spec:
  template:
    spec:
      containers:
        - name: synapse
          readinessProbe:
            httpGet:
              port: https
              scheme: HTTPS
            initialDelaySeconds: 80
            timeoutSeconds: 20
            periodSeconds: 20
            failureThreshold: 15
          livenessProbe:
            httpGet:
              port: https
              scheme: HTTPS
            initialDelaySeconds: 150
            timeoutSeconds: 30
            periodSeconds: 30
            failureThreshold: 15
          startupProbe:
            httpGet:
              port: https
              scheme: HTTPS
            initialDelaySeconds: 20
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 120
      volumes:
        - name: certs
          configMap:
            name: nishir-ca-certificates.crt
        - name: tls
          secret:
            secretName: matrix-tls
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
                mode: 0640
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-discord
spec:
  template:
    spec:
      volumes:
        - name: certs
          configMap:
            name: nishir-ca-certificates.crt
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-googlechat
spec:
  template:
    spec:
      volumes:
        - name: certs
          configMap:
            name: nishir-ca-certificates.crt
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-linkedin
spec:
  template:
    spec:
      volumes:
        - name: certs
          configMap:
            name: nishir-ca-certificates.crt
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-meta
spec:
  template:
    spec:
      volumes:
        - name: certs
          configMap:
            name: nishir-ca-certificates.crt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-proxy
spec:
  template:
    spec:
      volumes:
        - name: certs
          configMap:
            name: nishir-ca-certificates.crt
        - name: tls
          secret:
            secretName: matrix-proxy-tls
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
                mode: 0640
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-signal
spec:
  template:
    spec:
      volumes:
        - name: certs
          configMap:
            name: nishir-ca-certificates.crt
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-slack
spec:
  template:
    spec:
      volumes:
        - name: certs
          configMap:
            name: nishir-ca-certificates.crt
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-twitter
spec:
  template:
    spec:
      volumes:
        - name: certs
          configMap:
            name: nishir-ca-certificates.crt
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-whatsapp
spec:
  template:
    spec:
      volumes:
        - name: certs
          configMap:
            name: nishir-ca-certificates.crt
