apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forgero-tls
spec:
  commonName: forgero
  dnsNames:
    - forgero
  issuerRef:
    kind: ClusterIssuer
    name: nishir
  secretName: forgero-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
