apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - rclone/rclone.conf
    name: mautrix-meta-rclone
    namespace: shikanime
labels:
  - pairs:
      app.kubernetes.io/component: communication
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 1.140.0
resources:
  - ingress.yaml
  - sts.yaml
  - svc.yaml
images:
  - name: mautrix
    newName: dock.mau.dev/mautrix/meta
    newTag: v0.2602.0
