---
apiVersion: v1
kind: Service
metadata:
  name: mautrix-meta
spec:
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 29319
      targetPort: http
  selector:
    app.kubernetes.io/instance: mautrix-meta
    app.kubernetes.io/name: mautrix-meta
