apiVersion: v1
kind: Service
metadata:
  name: muatrix-meta
spec:
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 29319
      targetPort: http
  selector:
    app.kubernetes.io/name: muatrix-meta
