---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix-signal
spec:
  defaultBackend:
    service:
      name: mautrix-signal
      port:
        name: http
  tls:
    - hosts:
        - matrix-signal
