---
resources:
  - ingress.yaml
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
images:
  - name: mautrix
    newName: dock.mau.dev/mautrix/signal
    newTag: v0.2603.0
  - name: rclone
    newName: rclone/rclone
    newTag: 1.71.2
configMapGenerator:
  - name: mautrix-signal-rclone
    namespace: shikanime
    files:
      - rclone/rclone.conf
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: communication
      app.kubernetes.io/instance: mautrix-signal
      app.kubernetes.io/name: mautrix-signal
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 1.140.0
