---
apiVersion: v1
kind: Service
metadata:
  name: mautrix-signal
spec:
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 29328
      targetPort: http
  selector:
    app.kubernetes.io/name: mautrix-signal
