---
resources:
  - ../nishir
  - netpol.yaml
namespace: shikanime
patches:
  - path: patch-ingress.yaml
  - path: patch-svc.yaml
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: file-synchronizer
      app.kubernetes.io/instance: syncthing
      app.kubernetes.io/name: syncthing
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 2.0.12
