resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: metatube
    newName: ghcr.io/metatube-community/metatube-server
    newTag: 1.4.0
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "metatube", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$"
      } ]'
