apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-tofu-controller
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  deletionPolicy: Orphan
  interval: 10m
  path: ./infrastructure/tofu-controller/overlays/nishir
  prune: true
  sourceRef:
    name: flux-system
    kind: GitRepository
