apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  annotations:
    automata.shikanime.studio/images: '[ { "name": "hermes-agent-postgres", "tag-regex": "^(?P<version>.+)$" } ]'
images:
  - name: hermes-agent-postgres
    newName: pgvector/pgvector
    newTag: pg15
configMapGenerator:
  - files:
      - hermes-agent-postgres/init.sql
    name: hermes-agent-postgres
resources:
  - sts.yaml
  - svc.yaml
