---
resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "hermes-agent-postgres", "tag-regex": "^(?P<version>.+)$" } ]'
images:
  - name: hermes-agent-postgres
    newName: pgvector/pgvector
    newTag: pg15
configMapGenerator:
  - name: hermes-agent-postgres
    files:
      - hermes-agent-postgres/init.sql
labels:
  - includeTemplates: true
    includeVolumeClaimTemplates: true
    pairs:
      app.kubernetes.io/component: database
      app.kubernetes.io/instance: hermes-agent-postgres
      app.kubernetes.io/name: postgres
      app.kubernetes.io/part-of: nishir-automata
      app.kubernetes.io/version: "15"
