---
resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "hermes-agent-postgres", "tag-regex": "^(?P<version>.+)$" } ]'
images:
  - name: hermes-agent-postgres
    newName: pgvector/pgvector
    newTag: pg15
configMapGenerator:
  - name: hermes-agent-postgres
    files:
      - hermes-agent-postgres/init.sql
