apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-agent-postgres-data
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
