apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
  - name: sso-config
    literals:
      - LDAP_SERVER=openldap.shikanime.svc.cluster.local
      - LDAP_BASE_DN=dc=shikanime,dc=studio
      - LDAP_TLS=true
      - OIDC_ISSUER=https://dex.shikanime.ts.net
      - OIDC_SCOPES=openid email profile groups
