---
resources:
  - ../nishir
  - netpol.yaml
namespace: shikanime
patches:
  - path: patch-ingress.yaml
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: secret-manager
      app.kubernetes.io/instance: vaultwarden
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/part-of: nishir-security
      app.kubernetes.io/version: 1.35.4
