---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: flux
spec:
  statefulSet:
    pod:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: flux-operator
                  app.kubernetes.io/name: flux-operator
              namespaces:
                - flux-system
              topologyKey: kubernetes.io/hostname
