---
resources:
  - ingress.yaml
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "prowlarr", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$"
      } ]'
images:
  - name: prowlarr
    newName: lscr.io/linuxserver/prowlarr
    newTag: 2.3.0
