---
resources:
  - ingress.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "gitea-mirror", "tag-regex":
      "^(?P<version>v\\d+\\.\\d+\\.\\d+)$" } ]'
images:
  - name: gitea-mirror
    newName: ghcr.io/raylabshq/gitea-mirror
    newTag: v3.11.0
labels:
  - includeTemplates: true
    includeVolumeClaimTemplates: true
    pairs:
      app.kubernetes.io/component: version-control-server
      app.kubernetes.io/instance: gitea
      app.kubernetes.io/name: gitea-mirror
      app.kubernetes.io/part-of: nishir-platform
      app.kubernetes.io/version: 3.11.0
