apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forgejo-tls
spec:
  commonName: forgejo
  dnsNames:
    - forgejo
  issuerRef:
    kind: ClusterIssuer
    name: nishir
  secretName: forgejo-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
