resources:
  - ../../base
namespace: shikanime
components:
  - ../../components/monitoring
configMapGenerator:
  - name: honcho
    files:
      - honcho/config.toml
secretGenerator:
  - name: honcho
    envs:
      - honcho/.enc.env
