apiVersion: apps/v1
kind: Deployment
metadata:
  name: honcho
spec:
  template:
    spec:
      containers:
        - name: honcho
          volumeMounts:
            - name: config
              mountPath: /app/config.toml
              subPath: config.toml
      volumes:
        - name: config
          configMap:
            name: honcho
