---
resources:
  - ../../base
  - netpol.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime
patches:
  - path: patch-pvc.yaml
secretGenerator:
  - name: hermes-agent-postgres
    type: basic-auth
    envs:
      - hermes-agent-postgres/.enc.env
    options:
      disableNameSuffixHash: true
