apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime
patches:
  - path: patch-pvc.yaml
resources:
  - ../../base
  - netpol.yaml
secretGenerator:
  - envs:
      - hermes-agent-postgres/.enc.env
    name: hermes-agent-postgres
    options:
      disableNameSuffixHash: true
    type: basic-auth
