---
resources:
  - ../../base
namespace: shikanime
patches:
  - path: patch-pvc.yaml
secretGenerator:
  - name: hermes-agent-postgres
    type: basic-auth
    envs:
      - hermes-agent-postgres/.enc.env
    options:
      disableNameSuffixHash: true
