---
resources:
  - ../../base
  - cert.yaml
namespace: shikanime
components:
  - ../../components/tls
configurations:
  - namereference.yaml
patches:
  - path: patch-ingress.yaml
  - path: patch-pvc.yaml
secretGenerator:
  - name: prowlarr-pkcs12-password
    envs:
      - prowlarr/.enc.env
