apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: syncthing
spec:
  targetRefs:
    - name: syncthing
      group: ""
      kind: Service
  validation:
    caCertificateRefs:
      - name: syncthing-tls
        group: ""
        kind: Secret
    hostname: syncthing.taila659a.ts.net
