apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: syncthing
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: syncthing
  validation:
    caCertificateRefs:
      - group: ""
        kind: Secret
        name: syncthing-tls
    hostname: syncthing.taila659a.ts.net
