apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: shikanime
spec:
  template:
    spec:
      containers:
        - name: syncthing
          volumeMounts:
            - name: data-sync
              mountPath: /data/sync
            - name: data-camera
              mountPath: /data/Camera
            - name: data-datasets
              mountPath: /data/Datasets
            - name: data-studio
              mountPath: /data/Studio
            - name: data-sukebe
              mountPath: /data/Sukebe
            - name: data-videos
              mountPath: /data/Videos
      volumes:
        - name: data-sync
          persistentVolumeClaim:
            claimName: sync
        - name: data-camera
          persistentVolumeClaim:
            claimName: camera
        - name: data-datasets
          persistentVolumeClaim:
            claimName: datasets
        - name: data-sukebe
          persistentVolumeClaim:
            claimName: sukebe
        - name: data-videos
          persistentVolumeClaim:
            claimName: videos
