resources:
  - ../../base
  - backendtlspolicy.yaml
  - cert.yaml
  - httproute.yaml
  - tcproute.yaml
  - udproute.yaml
namespace: shikanime
components:
  - ../../components/tls
patches:
  - path: patch-pvc.yaml
  - path: patch-sts.yaml
