resources:
  - ../../base
  - cert.yaml
  - serverstransport.yaml
namespace: shikanime
components:
  - ../../components/tls
patches:
  - path: patch-httproute.yaml
  - path: patch-pvc.yaml
  - path: patch-sts.yaml
