---
resources:
  - ../nishir
  - netpol.yaml
namespace: shikanime
patches:
  - path: patch-ingress.yaml
secretGenerator:
  - name: mautrix-slack
    files:
      - config.yaml=matrix-slack/config.enc.yaml
      - doublepuppet.yaml=matrix-slack/doublepuppet.enc.yaml
      - registration.yaml=matrix-slack/registration.enc.yaml
    options:
      disableNameSuffixHash: true
