apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: copyparty
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: copyparty
      app.kubernetes.io/name: copyparty
  serviceName: copyparty
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: copyparty
        app.kubernetes.io/name: copyparty
    spec:
      containers:
        - name: copyparty
          image: copyparty
          livenessProbe:
            httpGet:
              path: /?reset=/._
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
          ports:
            - name: http
              containerPort: 3923
          readinessProbe:
            httpGet:
              path: /?reset=/._
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 180
            httpGet:
              path: /?reset=/._
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /cfg
      initContainers:
        - name: config-sync
          image: rclone
          args:
            - copyto
            - --copy-links
            - /mnt/startup-config/config.conf
            - /mnt/cfg/config.conf
          command:
            - rclone
          volumeMounts:
            - name: config
              mountPath: /mnt/cfg
            - name: rclone-config
              mountPath: /config/rclone/rclone.conf
              readOnly: true
              subPath: rclone.conf
            - name: startup-config
              mountPath: /mnt/startup-config
              readOnly: true
          securityContext:
            capabilities:
              add:
                - FOWNER
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: copyparty-config
        - name: rclone-config
          configMap:
            name: copyparty-rclone
        - name: startup-config
          configMap:
            name: copyparty
