apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../nishir
secretGenerator:
  - files:
      - config.yaml=matrix-whatsapp/config.enc.yaml
      - doublepuppet.yaml=matrix-whatsapp/doublepuppet.enc.yaml
      - registration.yaml=matrix-whatsapp/registration.enc.yaml
    name: matrix-whatsapp
    options:
      disableNameSuffixHash: true
