jobs:
  cleanup:
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    runs-on: ubuntu-slim
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: write
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-studio/actions/cleanup@v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
          pull-request-url: ${{ github.event.pull_request.html_url }}
name: Cleanup
"on":
  pull_request:
    types:
      - closed
permissions:
  contents: read
