jobs:
  nix:
    if: ${{ github.event_name == 'workflow_call' || github.event.pull_request.draft == false }}
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      OPERATOR_PRIVATE_KEY: ${{ secrets.OPERATOR_PRIVATE_KEY }}
    uses: ./.github/workflows/nix.yaml
    with:
      cachix-name: shikanime
  skaffold:
    if: ${{ github.event_name == 'workflow_call' || github.event.pull_request.draft == false }}
    secrets:
      OPERATOR_PRIVATE_KEY: ${{ secrets.OPERATOR_PRIVATE_KEY }}
    uses: ./.github/workflows/skaffold.yaml
name: Integration
'on':
  pull_request:
    branches:
      - main
      - gh/*/*/base
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false
      OPERATOR_PRIVATE_KEY:
        required: true
permissions:
  contents: read
