---
name: Nix
permissions:
  contents: read
"on":
  workflow_call:
    inputs:
      cachix-name:
        type: string
        default: ""
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false
      OPERATOR_PRIVATE_KEY:
        required: true
jobs:
  checks:
    name: Checks
    if: ${{ needs['setup-checks-jobs'].outputs.continue == 'true' }}
    runs-on: ${{ matrix.runner }}
    needs:
      - setup-checks-jobs
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs['setup-checks-jobs'].outputs.matrix) }}
    steps:
      - id: createGithubAppToken
        continue-on-error: true
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: read
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-studio/actions/nix/setup@v9
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          cachix-name: ${{ inputs['cachix-name'] }}
          github-token:
            ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN
            }}
      - uses: shikanime-studio/actions/checkout@v9
        with:
          github-token:
            ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN
            }}
      - id: direnv
        uses: shikanime-studio/actions/direnv@v9
      - env: ${{ fromJSON(steps.direnv.outputs.env) }}
        run:
          nix flake check --accept-flake-config --no-pure-eval --system "${{
          matrix.system }}"
        shell: bash
  packages:
    name: Packages
    if: ${{ needs['setup-packages-jobs'].outputs.continue == 'true' }}
    runs-on: ${{ matrix.runner }}
    needs:
      - setup-packages-jobs
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs['setup-packages-jobs'].outputs.matrix) }}
    steps:
      - id: createGithubAppToken
        continue-on-error: true
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: read
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-studio/actions/nix/setup@v9
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          cachix-name: ${{ inputs['cachix-name'] }}
          github-token:
            ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN
            }}
      - uses: shikanime-studio/actions/checkout@v9
        with:
          github-token:
            ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN
            }}
      - id: direnv
        uses: shikanime-studio/actions/direnv@v9
      - env: ${{ fromJSON(steps.direnv.outputs.env) }}
        run:
          nix build --accept-flake-config --no-pure-eval ".#packages.${{
          matrix.system }}.${{ matrix.name }}"
        shell: bash
  setup-checks-jobs:
    name: Setup Checks Jobs
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.setup-checks-jobs.outputs.continue }}
      matrix: ${{ steps.setup-checks-jobs.outputs.matrix }}
    steps:
      - id: createGithubAppToken
        continue-on-error: true
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: read
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-studio/actions/nix/setup@v9
        with:
          github-token:
            ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN
            }}
      - uses: shikanime-studio/actions/checkout@v9
        with:
          github-token:
            ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN
            }}
      - id: setup-checks-jobs
        uses: shikanime-studio/actions/nix/setup-checks-jobs@v9
  setup-packages-jobs:
    name: Setup Packages Jobs
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.setup-packages-jobs.outputs.continue }}
      matrix: ${{ steps.setup-packages-jobs.outputs.matrix }}
    steps:
      - id: createGithubAppToken
        continue-on-error: true
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: read
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-studio/actions/nix/setup@v9
        with:
          github-token:
            ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN
            }}
      - uses: shikanime-studio/actions/checkout@v9
        with:
          github-token:
            ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN
            }}
      - id: setup-packages-jobs
        uses: shikanime-studio/actions/nix/setup-packages-jobs@v9
