name: Release
permissions:
  contents: read
"on":
  push:
    branches:
      - main
      - release-[0-9]+.[0-9]+
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+*
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
      OPERATOR_PRIVATE_KEY:
        required: true
  workflow_dispatch:
    inputs:
      ref_name:
        description: Tag or branch to release
        required: true
jobs:
  nix:
    permissions:
      contents: read
      packages: write
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      OPERATOR_PRIVATE_KEY: ${{ secrets.OPERATOR_PRIVATE_KEY }}
    uses: ./.github/workflows/nix.yaml
    with:
      cachix-name: shikanime
  release:
    if:
      (startsWith(github.ref, 'refs/tags/v')) || (github.event_name ==
      'workflow_dispatch' && startsWith(github.event.inputs.ref_name, 'v'))
    needs:
      - skaffold
      - nix
    permissions:
      contents: write
    runs-on: ubuntu-slim
    steps:
      - id: createGithubAppToken
        continue-on-error: true
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: write
          permission-workflows: write
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-studio/actions/nix/setup@v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-studio/actions/checkout@v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-studio/actions/release@v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
          ref: ${{ github.ref_name || github.event.inputs.ref_name }}
          repo: ${{ github.repository }}
  skaffold:
    permissions:
      contents: read
      packages: write
    secrets:
      OPERATOR_PRIVATE_KEY: ${{ secrets.OPERATOR_PRIVATE_KEY }}
    uses: ./.github/workflows/skaffold.yaml
