apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      name: longhorn-ingress
      version: v1
      kind: Ingress
    patch: |
      - op: add
        path: /spec/tls
        value:
          - hosts:
              - nishir-longhorn
