appservice:
  id: discord
  address: http://mautrix-discord:29334
  as_token: ENC[AES256_GCM,data:kG4PmiH6KkQRG9UXHsJJKMWUk4tjkeCWoN43AqHaxlIPs1pacEPSMuyWwKuC1Zn7QjM1PhH5TRUQ1Rck6HMxyw==,iv:WB2qbkmFWZCT3+D+Zq/Rr9wKB3N+ql1UDSJzOEQACv0=,tag:N+Z5aN3rNVzxY8m3F/QDgw==,type:str]
  async_transactions: false
  ephemeral_events: true
  hostname: 0.0.0.0
  hs_token: ENC[AES256_GCM,data:eBNtQ0MsCiAoRIulqTHImbRlmlSiiNadR6DtRED64go+KggB2RcUgVNPaCsJWV9/zY4hHp1g+R20kkzg/l99Hw==,iv:1BeT6em1p3O9eR/6v1oL1blw6N4CGurWJIK21iNc15c=,tag:Ej/2TAJl6aSDQ764j1vqhg==,type:str]
  port: 29334
  bot:
    avatar: mxc://maunium.net/nIdEykemnwdisvHbpxflpDlC
    displayname: Discord bridge bot
    username: discordbot
  database:
    type: sqlite3-fk-wal
    max_conn_idle_time: null
    max_conn_lifetime: null
    max_idle_conns: 2
    max_open_conns: 20
    uri: file:/data/discord.db?_txlock=immediate
bridge:
  animated_sticker:
    args:
      fps: 25
      height: 320
      width: 320
    target: webp
  autojoin_thread_on_open: true
  avatar_proxy_key: ENC[AES256_GCM,data:wAKtbTu4xBgEIDJx+CKcczprY+7ngtppyHyHPQ7WN5M=,iv:Gi8495u7ke3nnpc5AFGEu05W32SOoyPBHjePZZpX9Jg=,tag:AFi2sezyWPNm2GV08LRSCw==,type:str]
  backfill:
    forward_limits:
      initial:
        channel: 50
        dm: 50
        thread: 50
      missed:
        channel: 500
        dm: 500
        thread: 500
    max_guild_members: -1
  cache_media: unencrypted
  channel_name_template:
    "{{if or (eq .Type 3) (eq .Type 4)}}{{.Name}}{{else}}#{{.Name}}{{end}}"
  command_prefix: "!discord"
  custom_emoji_reactions: true
  delete_guild_on_leave: true
  delete_portal_on_channel_delete: false
  delivery_receipts: false
  direct_media:
    allow_proxy: true
    enabled: false
    server_key: ENC[AES256_GCM,data:Rp7m2dstFZwvlwh14cdN/qKI6vHWh7vojzE/GIl+EFFs4hZvbV3j2CesnEUGObs4MCQlSee6gfcURg==,iv:YtEjkRZY4YfU26SxDEwOFfSe7WLaMznBwmTOCMd1Dwc=,tag:QWIrrDTGy4dYyQTGVIugMw==,type:str]
    server_name: matrix-discord-media.taila659a.ts.net
    well_known_response: null
  displayname_template:
    "{{if .Webhook}}Webhook{{else}}{{or .GlobalName .Username}}{{if .Bot}}
    (bot){{end}}{{end}}"
  double_puppet_allow_discovery: false
  double_puppet_server_map:
    matrix.taila659a.ts.net: https://matrix.taila659a.ts.net
  embed_fields_as_tables: true
  enable_webhook_avatars: false
  encryption:
    allow: true
    allow_key_sharing: false
    appservice: false
    default: true
    delete_keys:
      delete_fully_used_on_decrypt: true
      delete_on_device_delete: true
      delete_outbound_on_ack: false
      delete_outdated_inbound: true
      delete_prev_on_new_session: true
      dont_store_outbound: true
      periodically_delete_expired: true
      ratchet_on_decrypt: true
    msc4190: false
    plaintext_mentions: false
    require: false
    rotation:
      disable_device_change_key_rotation: false
      enable_custom: false
      messages: 100
      milliseconds: 6.048e+08
    self_sign: true
    verification_levels:
      receive: cross-signed-tofu
      send: cross-signed-tofu
      share: cross-signed-tofu
  federate_rooms: true
  guild_name_template: "{{.Name}}"
  login_shared_secret_map:
    matrix.taila659a.ts.net: ENC[AES256_GCM,data:2sE4XHnBlK9hRmlmAJQiKyPXua6SmX255PxvdhBog2g75sobR2V0Ral74tYXh1j83STuQQlx8ms3qmrdP5tjbg==,iv:QoREEn7UbO8ap35+lJXGXD1E415KecImXbw/8f1LKp0=,tag:2eCUZwqLhdgAHzzBi/A9uA==,type:str]
  management_room_text:
    additional_help: ""
    welcome: Hello, I'm a Discord bridge bot.
    welcome_connected: Use `help` for help.
    welcome_unconnected: Use `help` for help or `login` to log in.
  message_error_notices: true
  message_status_events: false
  mute_channels_on_create: false
  permissions:
    "*": relay
    "@root:matrix.taila659a.ts.net": admin
    matrix.taila659a.ts.net: user
  portal_message_buffer: 128
  prefix_webhook_messages: true
  private_chat_portal_meta: default
  provisioning:
    debug_endpoints: false
    prefix: /_matrix/provision
    shared_secret: ENC[AES256_GCM,data:aGT6JEM5X4+HqWpH0OXptdDhBBRk6AkyFEF5xx7tynz91HGa34KSJQa7tcYjSg1Ev/pATBJ9iGPIWCHktF9wdA==,iv:xmQiQlDsnmxPgQ7NT+7dXtBAB7VbNJVQLr2ELW07N+A=,tag:UNquxX8fdOLZowgeS5iCVQ==,type:str]
  proxy: null
  public_address: https://matrix-discord.taila659a.ts.net
  resend_bridge_info: false
  restricted_rooms: true
  startup_private_channel_create_limit: 5
  sync_direct_chat_list: false
  use_discord_cdn_upload: true
  username_template: discord_{{.}}
homeserver:
  address: https://synapse:8448
  async_media: false
  domain: matrix.taila659a.ts.net
  message_send_checkpoint_endpoint: null
  ping_interval_seconds: 0
  software: standard
  status_endpoint: null
  websocket: false
logging:
  min_level: debug
  writers:
    - type: stdout
      format: pretty-colored
    - type: file
      compress: true
      filename: ./logs/mautrix-discord.log
      format: json
      max_backups: 10
      max_size: 100
sops:
  version: 3.12.2
  encrypted_regex: ^(avatar_proxy_key|as_token|hs_token|pickle_key|server_key|shared_secret|signing_key|login_shared_secret_map|secrets)$
  lastmodified: "2026-04-14T23:43:33Z"
  mac: ENC[AES256_GCM,data:buKjRHyRu2L3hw+oyliFuk4ra5GOJLIjjH9OkTtzqKMhwcwnhws+BXEtuihOrKY7+bBkK7T3CuWqF2c60ePvJkdjOXgCkNTo/rpEOyhEyIoJcwrWLcA2oAwuc6IkKE0f3VYMpVzngBObAkbvCOCW/9T2EJDrvVyy0ail7PYxTDE=,iv:9yrVk82dvTNo1XsZswRXp1NOMadG3d7mGSPQXZKy9AA=,tag:iKme6+qoy5nNt9SQ1Wdz2A==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYXZtOEZMNUQ0bW9wSVJ3
        ellYRCtDSjV1RU5rYnowOUNBZTNCcXZXaUhRCmhmSXlRbHNlczErak14ZG1LYitQ
        T3lwaThBWXJMbGNwa1I1YVpmNVhtZjQKLS0tIDU0UnhxY1dTWG9tWHRHU3RrdzlU
        N2Vlc1YzNDUrSkxET01kME1Gb3pRMTgKM8PTxkxhmlhWS0pDwDMeOeATR29BNtj1
        4MASe6ziwdMp8efRYOlHLQpz3DlsoUEU2hiHx4QIFqLu6DobHCjGNQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dThEZ3Y2bHZPNFRtM08w
        Sjk1cUlCSk56UEVrSzFlZnN6ZnpQRkpiRDI4CkFxb210VEplVWpFdWFNaGFVRVVu
        aEU2cERQVVdxZWpOeVhzR2dObDNtSzQKLS0tIEhlQk5NZXI1OGZGbk5yRFE3RTF4
        TS9BeXRleU9vR0xKTGh0QXhjWnNRODQKzHc2ELMCx8iXgeGRxQ+KZuWQynC+tN+N
        iuYOU5mEG8AStMIAFzfhhBd+8B/JU7td5aZN5/y0i5NzBaWlZSN10g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZEZkUmQ2ZHZoSEEvOW5X
        VGRZSzNOaEdqYzhxOEZLMXFvNXN6OUNGa1FRCjFYTmFIdlZ3T2lMVGxydlBqT1hh
        citLbTZBOVBBOExiVjNiMXVHbDc3WHcKLS0tIFJhQWdBZEVEeDE3bTRTbkpPN1Rz
        b0poNVpPTXRlcUdnVEFpOE0vUERxYm8K4yvGCy9hUd5OM+oTEcjc/SR+pUxm6mio
        wi22AohRwFh+BhzAZUDUygeWPSX4Z4JG4jXcYafaTwhYdT1+cxE/Xw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
