apiVersion: v1
kind: Service
metadata:
  name: nishir-rw-tailnet
  annotations:
    tailscale.com/hostname: nishir-postgres
    tailscale.com/proxy-class: nishir-postgres
    tailscale.com/tags: tag:postgres
spec:
  loadBalancerClass: tailscale
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: nishir
    cnpg.io/instanceRole: primary
  type: LoadBalancer
