apiVersion: apps/v1
kind: Deployment
metadata:
  name: honcho
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: honcho
      app.kubernetes.io/name: honcho
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: honcho
        app.kubernetes.io/name: honcho
    spec:
      containers:
        - name: honcho
          image: honcho
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
            timeoutSeconds: 5
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 180
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /app/config.toml
              subPath: config.toml
          envFrom:
            - secretRef:
                name: honcho
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: honcho-postgres
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: honcho-postgres
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: honcho-postgres
                  key: database
            - name: DB_CONNECTION_URI
              value: postgresql+psycopg://$(DB_USER):$(DB_PASSWORD)@$(HONCHO_POSTGRES_SERVICE_HOST):$(HONCHO_POSTGRES_SERVICE_PORT)/$(DB_NAME)
      initContainers:
        - name: alembic-upgrade
          image: honcho
          command:
            - alembic
            - upgrade
            - head
          envFrom:
            - secretRef:
                name: honcho
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: honcho-postgres
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: honcho-postgres
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: honcho-postgres
                  key: database
            - name: DB_CONNECTION_URI
              value: postgresql+psycopg://$(DB_USER):$(DB_PASSWORD)@$(HONCHO_POSTGRES_SERVICE_HOST):$(HONCHO_POSTGRES_SERVICE_PORT)/$(DB_NAME)
      volumes:
        - name: config
          configMap:
            name: honcho
