resources:
  - deploy.yaml
  - hpa.yaml
  - netpol.yaml
  - svc.yaml
  - vpa.yaml
components:
  - components/monitoring
images:
  - name: honcho
    newName: ghcr.io/plastic-labs/honcho
    newTag: v3.0.9
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "honcho", "tag-regex": "^(?P<version>.+)$" } ]'
