---
resources:
  - ../nishir
  - netpol.yaml
namespace: shikanime
secretGenerator:
  - name: synapse
    files:
      - homeserver.yaml=synapse/homeserver.enc.yaml
      - synapse/matrix.taila659a.ts.net.log.config
